* Number-type: integer
* Description: Example with full row rank and optimal initial basic feasible solution having all artificial variables in the basis, thus forcing the expel procedure to pivot the artificial variables out of the basis
* Generated-by: Generated by LP_Test_Expel_Drive_Pivots.mw
NAME LP_Test_Expel_Drive_Pivots
ROWS
 N obj
 E c1
 E c2
 E c3
 E c4
COLUMNS
  x1  c1  -1
  x1  c2  0
  x1  c3  0
  x1  c4  0
  x1  obj  5
  x2  c1  0
  x2  c2  -1
  x2  c3  0
  x2  c4  0
  x2  obj  5
  x3  c1  0
  x3  c2  0
  x3  c3  -1
  x3  c4  0
  x3  obj  5
  x4  c1  0
  x4  c2  0
  x4  c3  0
  x4  c4  -1
  x4  obj  5
RHS
  rhs  c1  0
  rhs  c2  0
  rhs  c3  0
  rhs  c4  0
ENDATA
