* Number-type: integer
* Description: Example 8.1d from Chvatal
* Generated-by: Generated by Ub_LP_Chvatal_8_1_d_QPE_solver.mw
NAME Ub_LP_Chvatal_8_1_d_QPE_solver
ROWS
 N obj
 E c1
 E c2
 E c3
 E c4
 L c5
COLUMNS
  x1  c1  3
  x1  c2  -1
  x1  c3  1
  x1  c4  2
  x1  c5  2
  x1  obj  -8
  x2  c1  2
  x2  c2  2
  x2  c3  0
  x2  c4  -3
  x2  c5  0
  x2  obj  -6
  x3  c1  -1
  x3  c2  -2
  x3  c3  0
  x3  c4  2
  x3  c5  1
  x3  obj  2
  x4  c1  3
  x4  c2  0
  x4  c3  -3
  x4  c4  3
  x4  c5  0
  x4  obj  -6
  x5  c1  2
  x5  c2  0
  x5  c3  2
  x5  c4  0
  x5  c5  -1
  x5  obj  3
RHS
  rhs  c1  7
  rhs  c2  10
  rhs  c3  7
  rhs  c4  -10
  rhs  c5  -6
BOUNDS
  MI  BND  x3
  MI  BND  x4
  MI  BND  x5
ENDATA
