// #define CGAL_SURFACE_MESHER_EDGES_DEBUG_INTERSECTION
#define CGAL_SURFACE_MESHER_DEBUG_POLYHEDRAL_SURFACE_CONSTRUCTION
#define CGAL_SURFACE_MESHER_VERBOSE
// #define CGAL_POLYHEDRAL_SURFACE_VERBOSE_CONSTRUCTION
// #define CGAL_SURFACE_MESHER_EDGES_DEBUG_INSERTIONS
// #define CGAL_MESHES_DEBUG_REFINEMENT_POINTS
// #define CGAL_DEBUG_OCTREE_CONSTRUCTION
