#ifndef SCENE_EDIT_PATH_ITEM_CONFIG_H
#define SCENE_EDIT_PATH_ITEM_CONFIG_H

#ifdef scene_edit_path_item_EXPORTS
#  define SCENE_EDIT_PATH_ITEM_EXPORT Q_DECL_EXPORT
#else
#  define SCENE_EDIT_PATH_ITEM_EXPORT Q_DECL_IMPORT
#endif

#endif // SCENE_EDIT_PATH_ITEM_CONFIG_H
