Selective Nef Complex
standard
vertices   3
halfedges  2
facets     0
volumes    1
shalfedges 0
shalfloops 0
sfaces     3
0 { 0 0, -2 -2, 0 0, -2 | -1 0 0 1 } 1
1 { 1 1, -2 -2, 1 1, -2 | -1 0 0 2 } 1
2 { -2 -2, -2 -2, 2 2, -2 | 1 0 0 2 } 1
0 { 1, 0, 1 0 | 1 0 0 1 } 1
1 { 0, 1, 1 1 | -1 0 0 1 } 1
0 { 0 2 } 0
0 { 0, , 0 , , 0 } 0
1 { 1, , 1 , , 0 } 0
2 { 2, , , , 0 } 0
/* end Selective Nef complex */
