#ifndef SCENE_EDIT_BOX_ITEM_CONFIG_H
#define SCENE_EDIT_BOX_ITEM_CONFIG_H

#ifdef scene_edit_box_item_EXPORTS
#  define SCENE_EDIT_BOX_ITEM_EXPORT Q_DECL_EXPORT
#else
#  define SCENE_EDIT_BOX_ITEM_EXPORT Q_DECL_IMPORT
#endif

#endif // SCENE_EDIT_BOX_ITEM_CONFIG_H
