.TH CGAL_CREATE_MAKEFILE "1" "May 2006" "CGAL 3.3" "User Commands"
.SH NAME
cgal_create_makefile \- create makefiles for applications using CGAL
.SH SYNOPSIS
.B cgal_create_makefile
.BR -d | -t | -q
.RI [ filename ]
.SH DESCRIPTION
The script
.B cgal_create_makefile
allows the simple creation of makefiles for applications which use the CGAL
library. The generated rules contain the proper compiler and linker flags for
the CGAL library itself as well as for all libaries supported by CGAL. For each
source file with suffix
.I C
or
.IR cpp ,
a rule for the corresponding object file is generated. If the source file
contains a
.I main()
function, a rule for an executable is also generated (the script assumes that
each application consists of a single object file).
.SH OPTIONS
.PP
.TP
.B -d
Create a (default) makefile as described above.
.TP
.B -t
Create a makefile that is suited for the testsuite used by the CGAL developers.
.TP
.BR -q
Create a makefile with Qt support (including calls for the Qt's meta object
compiler moc.
.TP
.I filename
The output is written to
.I filename
(defaults to 
.IR makefile ).
If
.I filename
exists, it is renamed to
.IR filename .bak.
.SH ENVIRONMENT
.TP
.B CGAL_MAKEFILE
If
.B CGAL_MAKEFILE
is set, the compiler and linker flags are taken from this makefile template.
Otherwise, the default file
.I  /usr/share/cgal/makefile
is used.
.SH FILES
.I /usr/share/cgal/makefile
.RS
contains the default compiler and linker flags
.SH AUTHOR
The CGAL software was written by a large number of authors
(see /usr/share/doc/libcgal2/copyright for a list).

This manual page was written by Joachim Reichel <joachim.reichel@gmx.de> for
the Debian GNU/Linux system (but may be used by others).
.SH "REPORTING BUGS"
Report bugs to <cgal-discuss@lists-sop.inria.fr> (see http://www.cgal.org/
for further instructions).
.SH "SEE ALSO"
The full documentation for CGAL is available at http://www.cgal.org/ in PDF and
HTML format.
