./data/rooms_part1.dat ./data/rooms_part2.dat -sohgv
./data/comb_part1.dat ./data/comb_part2.dat -sohgv
./data/fork_part1.dat ./data/fork_part2.dat -sohv
./data/knife_part1.dat ./data/knife_part2.dat -sov
./data/mchain_part1.dat ./data/mchain_part2.dat -shv
./data/random_part1.dat ./data/random_part2.dat -sgv
./data/wheels_part1.dat ./data/wheels_part2.dat -hgv
./data/r35975_part1.dat ./data/r35975_part2.dat -sohgv
./data/r38305_part1.dat ./data/r38305_part2.dat -sohgv
./data/D.dat ./data/E.dat -sohgv
./data/F.dat ./data/G.dat -sohgv
./data/F.dat ./data/E.dat -sohgv
./data/F.dat ./data/D.dat -sohgv
./data/F.dat ./data/A.dat -sohgv
./data/A.dat ./data/G.dat -sohgv
./data/B.dat ./data/G.dat -sohgv
