#!/bin/sh

if [ ! -x "`which bibtex2html`" ]; then
    echo "You need to install bibtex2html first!"
    exit 1
fi

if [ ! -f "$1" ]; then
    echo "Usage: makebiblio path/to/manual-x.y.bib"
    echo "Note that the file manual-x.y.bib, with x.y equal to the current version of CGAL"
    echo "should be in the 'Manual' package, in Manual/doc_tex/Manual/..."
    exit 1
fi
bibtex2html -nodoc $1
mv ${1%.bib}_bib.html how_to_cite.html

cat > how_to_cite_cgal.txt <<'EOF'
/*!
\page how_to_cite_cgal Acknowledging %CGAL

%CGAL is implemented for the most part by researchers. The academic
world evaluates and rewards researchers for a good part by the
analysis of the number of published papers and the number of citations
of their papers, which measures their impact. In order to make the
%CGAL project attractive for researchers to contribute their work
(which allows users to benefit from new contributions), we are pushing
a model where the %CGAL manual chapters are considered like
publications, and can be cited in articles as such.

We therefore kindly ask users to cite %CGAL as appropriately as
possible in their papers, and to mention the use of %CGAL on the web
pages of their projects using %CGAL and provide us with links to these
web pages. Feel free to contact us in case you have any question or
remark on this topic.

We provide bibtex entries for the chapters of the User and Reference
Manual, as well as for publications directly related to the %CGAL
software.

## Citing the %CGAL Library or the %CGAL project ##

If you want to cite the %CGAL Library or project as a whole, please

- cite: %CGAL, Computational Geometry Algorithms Library, http://www.cgal.org 
- use the following <a href="how_to_cite.html">bibtex entry</a>.

## Citing the User and Reference Manual ##

If you want to refer to %CGAL manual, please cite the appropriate
  entry from the bibliographic entries for individual chapters listed
  in the table below.
EOF

footer="*/"

sed -e "s|https://cgal.geometryfactory.com/~pmoeller/Doxygen/CGAL.CGAL/html/||g" ${1%.bib}.html | sed -e "s|${1%.bib}_bib.html|how_to_cite.html|g" >> how_to_cite_cgal.txt
echo $footer >> how_to_cite_cgal.txt

echo 
echo "Do not forget to commit, now!"
