* Number-type: integer
* Description: LP with no constraints and two variables
* Generated-by: Generated by LP_no_cons_two_var_QPE_solver.mw
NAME LP_no_cons_two_var_QPE_solver
ROWS
 N obj
COLUMNS
  x1  obj  -1
  x2  obj  1
RHS
ENDATA
