* Number-type: integer
* Description: Example 8.1b from Chvatal
* Generated-by: Generated by Ub_LP_Chvatal_8_1_b_QPE_solver.mw
NAME Ub_LP_Chvatal_8_1_b_QPE_solver
ROWS
 N obj
 L c1
 L c2
 L c3
 L c4
COLUMNS
  x1  c1  1
  x1  c2  1
  x1  c3  1
  x1  c4  1
  x1  obj  -3
  x2  c1  4
  x2  c2  3
  x2  c3  2
  x2  c4  3
  x2  obj  -1
  x3  c1  3
  x3  c2  -1
  x3  c3  3
  x3  c4  -2
  x3  obj  -4
  x4  c1  3
  x4  c2  1
  x4  c3  2
  x4  c4  1
  x4  obj  -2
RHS
  rhs  c1  2
  rhs  c2  -2
  rhs  c3  3
  rhs  c4  -3
BOUNDS
  MI  BND  x1
  MI  BND  x2
ENDATA
