version = 1
SPDX-PackageName = "CGAL"
SPDX-PackageSupplier = "CGAL Editorial Board <info@cgal.org>"
SPDX-PackageDownloadLocation = "https://github.com/CGAL/cgal"

[[annotations]]
path = [
        ".**",
        "**.cmake",
        "**.md",
        ".github/**",
        "Maintenance/**",
        "**/TODO",
        "**/doc/**",
        "**/deb/**",
        "**/applications/**",
        "**/doc_html/**",
        "**/scripts/**",
        "**/developer_scripts/**",
        "**/demo/**",
        "**/examples/**",
        "**/src/**",
        "**/test/**",
        "**/benchmarks/**",
        "**/benchmark/**",
        "**/package_info/**",
        "**/data/**",
        "**/cmake/**",
        "**/*.natvis",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "1995-2024 The CGAL Project"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
        "REUSE.toml",
        "CMakeLists.txt",
        "cmake_uninstall.cmake.in",
        "GraphicsView/include/CGAL/Qt/ImageInterface.ui",
        "GraphicsView/include/CGAL/Qt/resources/qglviewer-icon.xpm",
        "Installation/AUTHORS",
        "Installation/CMakeLists.txt",
        "Installation/README",
        "Installation/auxiliary/cgal_create_cmake_script.1",
        "Installation/auxiliary/gmp/README",
        "Installation/include/CGAL/license/gpl_package_list.txt",
        "copyright",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "1995-2024 The CGAL Project"
SPDX-License-Identifier = "CC0-1.0"
