#!/bin/sh
CGAL_ROOT="/cygdrive/c/cgal/test"

# Remove test results older than 5 days.
# The pattern "../test/" after "$CGAL_ROOT" tries to protect against a
# catastrophic `rm -rf` is "$CGAL_ROOT" happens to be empty.
find "$CGAL_ROOT/../test" -maxdepth 1 -type d -name 'CGAL*' ! -ctime -5 -exec rm -rf '{}' \;

BUILD_HOSTS="localhost"
REFERENCE_PLATFORMS_DIR="c:/cgal/reference_platforms"
CGAL_TESTER="afabri"
CGAL_TESTER_NAME="picasso (GF)"
CGAL_TESTER_ADDRESS="andreas.fabri@geometryfactory.com"

COMPILERS_localhost=""
COMPILERS_localhost="$COMPILERS_localhost x64_Cygwin-Windows8_MSVC2012-Release-32bits"
COMPILERS_localhost="$COMPILERS_localhost x64_Cygwin-Windows8_MSVC2012-Release-64bits"
COMPILERS_localhost="$COMPILERS_localhost x64_Cygwin-Windows8_MSVC2012-Debug-64bits"
COMPILERS_localhost="$COMPILERS_localhost x64_Cygwin-Windows8_MSVC2013-Release-32bits"
#COMPILERS_localhost="$COMPILERS_localhost x64_Cygwin-Windows8_MSVC2013-Release-64bits"
#COMPILERS_localhost="$COMPILERS_localhost x64_Cygwin-Windows8_MSVC2013-Debug-64bits"
COMPILERS_localhost="$COMPILERS_localhost x64_Cygwin-Windows8_MSVC2013-Debug-32bits"
#COMPILERS_localhost="$COMPILERS_localhost x64_Cygwin-Windows8_MSVC2010-Debug-32bits"
#COMPILERS_localhost="$COMPILERS_localhost x64_Cygwin-Windows8_MSVC2010-Release-64bits"
#COMPILERS_localhost="$COMPILERS_localhost x64_Cygwin-Windows8_MSVC2010-Release-64bits-LEDA"
#COMPILERS_localhost="$COMPILERS_localhost x64_Cygwin-Windows8_MSVC2008-Debug-64bits"
#COMPILERS_localhost="$COMPILERS_localhost x64_Cygwin-Windows8_MSVC2008-Release-32bits"

MYSHELL="bash --login"
FTP_OPTS="-v -n"
PROCESSORS_localhost="7"

UPLOAD_RESULT_DESTINATION="cgaltest@cgaltest.geometryfactory.com:incoming"
WGET_OPTS="--no-verbose"
