
cd demo\Alpha_shapes_2 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Arrangement_2 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Benchmark_LK_LEDA 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Fixed_precision_nt 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Generator_LEDA 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\GeoWin 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Matrix_search 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Min_circle_2 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Min_ellipse_2 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Min_quadrilateral_2 
%MMAKE% clean
%MMAKE% all  
cd ..\..
cd demo\Planar_map 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Planar_map_Bbox
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Point_set_2 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Polygon 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Polyhedron_IO 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Robustness
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Stream_support_LEDA 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Triangulation 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Triangulation3 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Window_stream 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 

