cd demo\Alpha_shapes_2 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Arrangement_2 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Convex_hull_2
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Convex_hull_3
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Convex_hull_d
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Fixed_precision_nt 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Generator
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\GeoWin 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Matrix_search 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Min_circle_2 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Min_ellipse
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Min_quadrilateral_2 
%MMAKE% clean
%MMAKE% all  
cd ..\..
cd demo\Planar_map 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Planar_map_Bbox
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Point_set_2 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Polygon 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Polyhedron_IO 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Robustness
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Stream_support_LEDA 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Triangulation_2 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Triangulation_3 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd demo\Window_stream 
%MMAKE% clean
%MMAKE% all  
cd ..\.. 


