
if(OpenMesh_FOUND AND NOT TARGET CGAL::OpenMesh_support)

  add_library(CGAL::OpenMesh_support UNKNOWN IMPORTED)

  set_target_properties(OpenMesh::OpenMesh PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS "CGAL_USE_OPENMESH;NOMINMAX;_USE_MATH_DEFINES"
    INTERFACE_INCLUDE_DIRECTORIES  "${OPENMESH_INCLUDE_DIRS}")

  if(OPENMESH_CORE_LIBRARY_RELEASE)
    set_property(TARGET OpenMesh::OpenMesh APPEND PROPERTY
      IMPORTED_CONFIGURATIONS RELEASE)
    set_target_properties(OpenMesh::OpenMesh PROPERTIES
      IMPORTED_LOCATION_RELEASE "${OPENMESH_CORE_LIBRARY_RELEASE}")
  endif()

  if(OPENMESH_CORE_LIBRARY_DEBUG)
    set_property(TARGET OpenMesh::OpenMesh APPEND PROPERTY
      IMPORTED_CONFIGURATIONS DEBUG)
    set_target_properties(OpenMesh::OpenMesh PROPERTIES
      IMPORTED_LOCATION_DEBUG "${OPENMESH_CORE_LIBRARY_DEBUG}")
  endif()
endif()
