if(SCIP_FOUND AND NOT TARGET CGAL::SCIP_support)
  add_library(CGAL::SCIP_support INTERFACE IMPORTED)
  set_target_properties(CGAL::SCIP_support PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS "CGAL_USE_SCIP"
    INTERFACE_INCLUDE_DIRECTORIES "${SCIP_INCLUDE_DIRS}"
    INTERFACE_LINK_LIBRARIES "${SCIP_LIBRARIES}")
endif()
