if(libpointmatcher_FOUND AND NOT TARGET CGAL::pointmatcher_support)
  add_library(CGAL::pointmatcher_support INTERFACE IMPORTED)
  target_compile_definitions(CGAL::pointmatcher_support INTERFACE "CGAL_LINKED_WITH_POINTMATCHER")
  target_include_directories(CGAL::pointmatcher_support INTERFACE "${libpointmatcher_INCLUDE_DIR}")
  target_link_libraries(CGAL::pointmatcher_support INTERFACE "${libpointmatcher_LIBRARIES}")
endif()
