if(OpenCV_FOUND AND NOT TARGET CGAL::OpenCV_support)
  add_library(CGAL::OpenCV_support INTERFACE IMPORTED)
  set_target_properties(CGAL::OpenCV_support PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS "CGAL_LINKED_WITH_OPENCV"
    INTERFACE_INCLUDE_DIRECTORIES "${OpenCV_INCLUDE_DIRS}"
    INTERFACE_LINK_LIBRARIES "${OpenCV_LIBS}")
endif()
