if(GLPK_FOUND AND NOT TARGET CGAL::GLPK_support)
  add_library(CGAL::GLPK_support INTERFACE IMPORTED)
  set_target_properties(CGAL::GLPK_support PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS "CGAL_USE_GLPK"
    INTERFACE_INCLUDE_DIRECTORIES "${GLPK_INCLUDE_DIR}"
    INTERFACE_LINK_LIBRARIES "${GLPK_LIBRARIES}")
endif()
