if(ITK_FOUND AND NOT TARGET CGAL::ITK_support)
  add_library(CGAL::ITK_support INTERFACE IMPORTED)
  set_target_properties(CGAL::ITK_support PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS "CGAL_USE_ITK"
    INTERFACE_INCLUDE_DIRECTORIES "${ITK_INCLUDE_DIRS}"
    INTERFACE_LINK_LIBRARIES "${ITK_LIBRARIES}")
endif()
