if(OpenGR_FOUND AND NOT TARGET CGAL::OpenGR_support)
  add_library(CGAL::OpenGR_support INTERFACE IMPORTED)
  set_target_properties(CGAL::OpenGR_support PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS "CGAL_LINKED_WITH_OPENGR"
    INTERFACE_INCLUDE_DIRECTORIES "${OpenGR_INCLUDE_DIR}")
endif()
