if (CGAL_target_use_TensorFlow_included)
  return()
endif()
set(CGAL_target_use_TensorFlow_included TRUE)

function(CGAL_target_use_TensorFlow target)
  target_include_directories(${target} PUBLIC ${TensorFlow_INCLUDE_DIR})
  target_compile_options( ${target} PUBLIC -DCGAL_LINKED_WITH_TENSORFLOW)
  target_link_libraries(${target} PUBLIC ${TensorFlow_LIBRARU})
endfunction()
