if(LASLIB_FOUND AND NOT TARGET CGAL::LASLIB_support)
  add_library(CGAL::LASLIB_support INTERFACE IMPORTED)
  set_target_properties(CGAL::LASLIB_support PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS "CGAL_LINKED_WITH_LASLIB"
    INTERFACE_INCLUDE_DIRECTORIES "${LASLIB_INCLUDE_DIR};${LASZIP_INCLUDE_DIR}"
    INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "${LASLIB_INCLUDE_DIR};${LASZIP_INCLUDE_DIR}"
    INTERFACE_LINK_LIBRARIES "${LASLIB_LIBRARIES}")
endif()
