if (CGAL_target_use_OpenCV_included)
  return()
endif()
set(CGAL_target_use_OpenCV_included TRUE)

function(CGAL_target_use_OpenCV target)
  target_include_directories(${target} PUBLIC ${OpenCV_INCLUDE_DIRS})
  target_compile_options( ${target} PUBLIC -DCGAL_LINKED_WITH_OPENCV)
  target_link_libraries(${target} PUBLIC ${OpenCV_LIBS})
endfunction()
