if(CERES_FOUND AND NOT TARGET CGAL::Ceres_support)
  add_library(CGAL::Ceres_support INTERFACE IMPORTED)
  set_target_properties(CGAL::Ceres_support PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS "CGAL_PMP_USE_CERES_SOLVER"
    INTERFACE_INCLUDE_DIRECTORIES "${CERES_INCLUDE_DIRS}"
    INTERFACE_LINK_LIBRARIES "ceres")
endif()
