if(ITK_FOUND AND NOT TARGET CGAL::ITK_support)
  add_library(CGAL::ITK_support INTERFACE IMPORTED)
  foreach(itk_target ITKCommon ITKSmoothing ITKImageIntensity)
    if(TARGET ${itk_target})
      target_link_libraries(CGAL::ITK_support INTERFACE ${itk_target})
    endif()
  endforeach()
  target_compile_definitions(CGAL::ITK_support INTERFACE CGAL_USE_ITK)
endif()
