if(CGAL_SetupCGAL_CoreDependencies_included)
  return()
endif()
set(CGAL_SetupCGAL_CoreDependencies_included TRUE)

if(NOT CGAL_DISABLE_GMP)
  include(CGAL_SetupGMP)
  if(GMP_FOUND)
    set(CGAL_Core_FOUND TRUE)
  endif()
endif()

function(CGAL_setup_CGAL_Core_dependencies target)
  if(ARGV1 STREQUAL INTERFACE)
    set(keyword INTERFACE)
  else()
    set(keyword PUBLIC)
  endif()
  use_CGAL_GMP_support(CGAL_Core ${keyword})
  target_link_libraries( CGAL_Core ${keyword} CGAL::CGAL )
endfunction()
