if(METIS_FOUND AND NOT TARGET CGAL::METIS_support)
  add_library(CGAL::METIS_support INTERFACE IMPORTED)
  set_target_properties(CGAL::METIS_support PROPERTIES
  	INTERFACE_COMPILE_DEFINITIONS "CGAL_METIS_ENABLED"
    INTERFACE_INCLUDE_DIRECTORIES "${METIS_INCLUDE_DIRS}"
    INTERFACE_LINK_LIBRARIES "${METIS_LIBRARIES}")
endif()
