if(LIB3MF_FOUND AND NOT TARGET CGAL::lib3mf_support)
  add_library(CGAL::lib3mf_support INTERFACE IMPORTED)
  set_target_properties(CGAL::lib3mf_support PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS "CGAL_LINKED_WITH_LIB3MF"
    INTERFACE_INCLUDE_DIRECTORIES "${LIB3MF_INCLUDE_DIR}"
    INTERFACE_LINK_LIBRARIES "${LIB3MF_LIBRARIES}")
endif()
