#!/bin/csh -f
# +---------------------------------------------------------------+
# |   prepare_test for test1                                      |
# +---------------------------------------------------------------+

# Prepare test suit for the tools around the cc_manual.sty 
# for C++ manual writing.
# ------------------------------------------------------------------------

# Test of the extraction
cc_extract Point_2.tex > Point_2.ori.ex

# Test of the manual production
cc_manual_to_html -release "Release 1.6" -date "Date" -cgal_dir . Point_2.tex
mv CGAL_Point_2.html  CGAL_Point_2.ori.html
mv contents.html      contents.ori.html
mv manual_index.html  manual_index.ori.html
#   rm CGAL_Point_2.html contents.html manual_index.html 
rm *.gif


