# script generated by Insure++
# Run -c -g -I../../include -I../../../Mesh_2/include -I../../../Mesh_3/include -I../../../Triangulation_3/include -Wall -DCGAL_USE_GMP -DCGAL_USE_GMPXX -DCGAL_USE_CORE -DCGAL_USE_QT -I/home/drey/src/Geometrica_2003-2004/CGAL-3.2-I-9/include/CGAL/config/i686_Linux-2.6.10-1.741-FC3_g++-3.4.2 -I/home/drey/src/Geometrica_2003-2004/CGAL-3.2-I-9/include -I/usr/lib/qt-3.3/include -c surface_mesher.C
proc GetExtraMpfArgs { args } {
    if { $args == {surface_mesher.C} } { 
        return { -si {initfuncname _insight_I7_0_gcc_surfaceWmesher1110362187} }
    } else {
         return {};
    }
}
