#ifndef CGAL_SEGMENT_DELAUNAY_GRAPH_LINF_2_BASIC_H
#define CGAL_SEGMENT_DELAUNAY_GRAPH_LINF_2_BASIC_H

#include <CGAL/basic.h>

#define CGAL_SEGMENT_DELAUNAY_GRAPH_LINF_2_NS \
  CGAL::SegmentDelaunayGraphLinf_2

#endif // CGAL_SEGMENT_DELAUNAY_GRAPH_LINF_2_BASIC_H
