Import('dsrenv')
files=[
        SConscript( 'demo/SConscript' ),
        SConscript( 'doc/SConscript' ),
        SConscript( 'doc_doxygen/SConscript' ),
        SConscript( 'doc_doxygen.out/SConscript' ),
        SConscript( 'examples/SConscript' ),
        SConscript( 'include/SConscript' ),
        SConscript( 'lib_accel/SConscript' ),
        SConscript( 'src/SConscript' ),
        SConscript( 'test/SConscript' ),
      ]
Return('files')
