#!/sw/bin/perl

#use strict

my $pckge='aapje';
my $vrsion;

format STDOUT =
               @<<<<<<<<<<<<<<<<<<<<<<< @<<<<<<<<<<<<<<<<<<<<<<<<<
               $pckge,                  $vrsion
.

#$~ = "Nice_Output";

while(<STDIN>) {
    if (m/^\s*(.*?)\s*:\s*(.*?)\s*$/) {
	($pckge,$vrsion) = ($1,$2);
	#print STDERR $pckge, $vrsion,"\n";
	write;
    }
}

