#!/bin/sh

cd .. ;

rm -f Aff_transformationC3.h
rm -f DirectionC3.h
rm -f LineC3.h
rm -f PlaneC3.h
rm -f PointC3.h
rm -f RayC3.h
rm -f SegmentC3.h
rm -f TetrahedronC3.h
rm -f TriangleC3.h
rm -f VectorC3.h
rm -f basic_constructionsC3.h
rm -f basic_constructions_ftC3.h
rm -f distance_predicatesC3.h
rm -f predicates_on_ftC3.h
rm -f predicates_on_pointsC3.h
rm -f solveC3.h

rm -f Aff_transformation_3.h
rm -f Direction_3.h
rm -f Line_3.h
rm -f Plane_3.h
rm -f Point_3.h
rm -f Ray_3.h
rm -f Segment_3.h
rm -f Tetrahedron_3.h
rm -f Triangle_3.h
rm -f Vector_3.h
rm -f basic_constructions_3.h
rm -f basic_constructions_ft_3.h
rm -f distance_predicates_3.h
rm -f predicates_on_ft_3.h
rm -f predicates_on_points_3.h
rm -f solve_3.h
