// Copyright (c) 2026 Tel-Aviv University (Israel).
// All rights reserved.
// This file is part of CGAL (www.cgal.org).
// SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-Commercial
// Author(s): Efi Fogel         <efifogel@gmail.com>

#ifndef CGAL_ARRANGEMENT_ON_CURVE_1_ARRANGEMENT_ON_CURVE_1_H
#define CGAL_ARRANGEMENT_ON_CURVE_1_ARRANGEMENT_ON_CURVE_1_H

#include <CGAL/license/Arrangement_on_curve_1.h>

#include <variant>
#include <memory>

#include <CGAL/Arrangement_on_curve_1/Unbounded_topology_traits.h>

namespace CGAL {
namespace Arrangement_on_curve_1 {

template <typename GeometryTraits_1,
          typename TopologyTraits = Unbounded_topology_traits<typename GeometryTraits_1::Point_1>>
class Arrangement_on_curve_1 {
public:
  using Geometry_traits_1 = GeometryTraits_1;
  using Topology_traits = TopologyTraits;

  // Define a clean type alias for the traits smart pointer
  using Shared_geometry_traits = std::shared_ptr<const Geometry_traits_1>;

  using Point_1 = typename Geometry_traits_1::Point_1;

  using Vertex_descriptor = typename Topology_traits::Vertex_descriptor;
  using Edge_descriptor = typename Topology_traits::Edge_descriptor;

  using Vertex_const_descriptor = typename Topology_traits::Vertex_const_descriptor;
  using Edge_const_descriptor = typename Topology_traits::Edge_const_descriptor;

  // Location result: a point is either ON a vertex or INSIDE an edge
  using Location_result = std::variant<Vertex_descriptor, Edge_descriptor>;
  using Const_location_result = std::variant<Vertex_const_descriptor, Edge_const_descriptor>;

private:
  Shared_geometry_traits m_geometry_traits;
  Topology_traits m_topology_traits;

public:
  // --------------------------------------------------------------------------
  // Special member functions.
  //
  // The destructor, move constructor, and move assignment are all correct as
  // generated by the compiler: shared_ptr and TopologyTraits both have correct
  // move semantics (std::list moves without invalidating iterators).
  //
  // The copy constructor and copy assignment must be explicitly defaulted here
  // (rather than left fully implicit) so that their correctness is visible and
  // intentional: they delegate entirely to TopologyTraits's copy operations,
  // which perform the non-trivial cross-reference patching needed to produce a
  // fully independent copy with valid internal iterators.
  // --------------------------------------------------------------------------
  ~Arrangement_on_curve_1() = default;

  Arrangement_on_curve_1(const Arrangement_on_curve_1&) = default;
  Arrangement_on_curve_1& operator=(const Arrangement_on_curve_1&) = default;

  Arrangement_on_curve_1(Arrangement_on_curve_1&&) noexcept = default;
  Arrangement_on_curve_1& operator=(Arrangement_on_curve_1&&) noexcept = default;

  // 1. Default constructor: allocates a default-constructed traits instance on the heap
  Arrangement_on_curve_1() :
    m_geometry_traits(std::make_shared<const Geometry_traits_1>()),
    m_topology_traits()
  {}

  // 2. Constructor passing an existing smart pointer
  Arrangement_on_curve_1(Shared_geometry_traits shared_geom_tr) :
    m_geometry_traits(std::move(shared_geom_tr)),
    m_topology_traits()
  { CGAL_assertion(m_geometry_traits != nullptr); }

  // 3. Fully custom constructor with topology traits
  Arrangement_on_curve_1(Shared_geometry_traits shared_geom_tr, Topology_traits topo_tr) :
    m_geometry_traits(std::move(shared_geom_tr)),
    m_topology_traits(std::move(topo_tr))
  { CGAL_assertion(m_geometry_traits != nullptr); }

  // ACCESSORS
  const Geometry_traits_1& geometry_traits_1() const { return *m_geometry_traits; }
  Shared_geometry_traits shared_geometry_traits_1() const { return m_geometry_traits; }

  const Topology_traits& topology_traits() const { return m_topology_traits; }
  Topology_traits& topology_traits() { return m_topology_traits; }

  bool is_empty() const { return m_topology_traits.is_empty(); }
  size_t number_of_vertices() const { return m_topology_traits.number_of_vertices(); }
  size_t number_of_edges() const { return m_topology_traits.number_of_edges(); }

  auto vertices() const { return m_topology_traits.vertices(); }
  auto edges() const { return m_topology_traits.edges(); }

  auto vertex_point_map() const { return m_topology_traits.vertex_point_map(); }
  auto vertex_data_map() const { return m_topology_traits.vertex_data_map(); }
  auto edge_data_map() const { return m_topology_traits.edge_data_map(); }

  Edge_descriptor unbounded_left_edge() { return m_topology_traits.unbounded_left_edge(); }
  Edge_const_descriptor unbounded_left_edge() const { return m_topology_traits.unbounded_left_edge(); }
  Edge_descriptor unbounded_right_edge() { return m_topology_traits.unbounded_right_edge(); }
  Edge_const_descriptor unbounded_right_edge() const { return m_topology_traits.unbounded_right_edge(); }

  Vertex_descriptor left_vertex(Edge_descriptor e) { return m_topology_traits.left_vertex(e); }
  Vertex_descriptor right_vertex(Edge_descriptor e) { return m_topology_traits.right_vertex(e); }
  Edge_descriptor left_edge(Vertex_descriptor v) { return m_topology_traits.left_edge(v); }
  Edge_descriptor right_edge(Vertex_descriptor v) { return m_topology_traits.right_edge(v); }

  Vertex_const_descriptor left_vertex(Edge_const_descriptor e) const { return m_topology_traits.left_vertex(e); }
  Vertex_const_descriptor right_vertex(Edge_const_descriptor e) const { return m_topology_traits.right_vertex(e); }
  Edge_const_descriptor left_edge(Vertex_const_descriptor v) const{ return m_topology_traits.left_edge(v); }
  Edge_const_descriptor right_edge(Vertex_const_descriptor v) const { return m_topology_traits.right_edge(v); }

  bool has_left_vertex(Edge_const_descriptor e) const { return m_topology_traits.has_left_vertex(e); }
  bool has_right_vertex(Edge_const_descriptor e) const { return m_topology_traits.has_right_vertex(e); }

  // Setters
  void reset_shared_geometry_traits(Shared_geometry_traits new_shared_geom_tr) {
    // Safety check: changing traits on a populated structure is highly dangerous
    CGAL_precondition_msg(is_empty(), "Cannot reset the geometry traits pointer of a non-empty arrangement.");
    CGAL_assertion(new_shared_geom_tr != nullptr);
    m_geometry_traits = new_shared_geom_tr;
  }

  // ============================================================================
  // HIGH-LEVEL TOPOLOGICAL OPERATIONS
  // ============================================================================

  // Insert the very first vertex into an empty arrangement.
  // The single unbounded edge is split into: (-inf, v) and (v, +inf).
  Vertex_descriptor insert_empty(const Point_1& p) {
    auto& topo = m_topology_traits;

    // The arrangement must be empty: one unbounded edge exists.
    auto e_unbounded = topo.unbounded_left_edge();

    Vertex_descriptor v = topo.create_vertex(p);

    // Create the right new edge: (v, +inf)
    Edge_descriptor e_right = topo.create_edge();

    // Reuse e_unbounded as the left edge: (-inf, v)
    // It already has no left vertex; set its right vertex to v.
    topo.set_right_vertex(e_unbounded, v);

    // The right edge has v as its left vertex, and no right vertex.
    topo.set_left_vertex(e_right, v);

    // Wire the vertex to its two adjacent edges.
    topo.set_left_edge(v, e_unbounded);
    topo.set_right_edge(v, e_right);

    // Explicitly update the right boundary tracker.
    topo.set_unbounded_right_edge(e_right);

    return v;
  }

  // Insert a new vertex p strictly to the left of an existing first vertex v_first.
  Vertex_descriptor insert_before(Vertex_descriptor v, const Point_1& p) {
    auto& topo = m_topology_traits;

    Edge_descriptor e_left = topo.left_edge(v);
    Vertex_descriptor v_new = topo.create_vertex(p);

    // Create a new edge to sit between v_new and v: (v_new, v)
    Edge_descriptor e_between = topo.create_edge();
    topo.set_left_vertex(e_between, v_new);
    topo.set_right_vertex(e_between, v);

    // The old left edge now terminates at v_new on its right
    topo.set_right_vertex(e_left, v_new);

    // v_new sits between e_left and e_between.
    topo.set_left_edge(v_new, e_left);
    topo.set_right_edge(v_new, e_between);

    // v's left edge is now e_between.
    topo.set_left_edge(v, e_between);

    return v_new;
  }

  // Insert a new vertex p strictly to the right of an existing last vertex v.
  Vertex_descriptor insert_after(Vertex_descriptor v, const Point_1& p) {
    auto& topo = m_topology_traits;

    Edge_descriptor e_right = topo.right_edge(v);
    Vertex_descriptor v_new = topo.create_vertex(p);

    // Create a new edge to sit between v_new and v: (v_new, v)
     Edge_descriptor e_between = topo.create_edge();
    topo.set_left_vertex(e_between, v);
    topo.set_right_vertex(e_between, v_new);

    // The old right edge now starts from v_new
    topo.set_left_vertex(e_right, v_new);

    // v_new is wired between e_between and e_right.
    topo.set_left_edge(v_new, e_between);
    topo.set_right_edge(v_new, e_right);

    // v's right edge is now e_between.
    topo.set_right_edge(v, e_between);

    return v_new;
  }

  // Split the edge e by inserting a new vertex p inside it.
  // e becomes the left sub-edge; a new edge becomes the right sub-edge.
  Vertex_descriptor split_edge(Edge_descriptor e, const Point_1& p) {
     auto& topo = m_topology_traits;

    Vertex_descriptor v_new = topo.create_vertex(p);
    Edge_descriptor e_right = topo.create_edge();

    // If e has a right vertex, transfer it to e_right.
    if (topo.has_right_vertex(e)) {
      Vertex_descriptor v_old_right = topo.right_vertex(e);
      topo.set_right_vertex(e_right, v_old_right);
      topo.set_left_edge(v_old_right, e_right);
    }
    // e_right's left vertex is v_new.
    topo.set_left_vertex(e_right, v_new);

    // e (the left sub-edge) now ends at v_new.
    topo.set_right_vertex(e, v_new);

    // Wire v_new between e and e_right.
    topo.set_left_edge(v_new, e);
    topo.set_right_edge(v_new, e_right);

    return v_new;
  }

  // Remove vertex v from the arrangement.
  // Merge its two adjacent edges into one, keeping the left edge and removing the right.
  void remove(Vertex_descriptor v) {
    auto& topo = m_topology_traits;

    Edge_descriptor e_left  = topo.left_edge(v);
    Edge_descriptor e_right = topo.right_edge(v);

    // Extend e_left to cover the span formerly covered by e_right.
    if (topo.has_right_vertex(e_right)) {
      Vertex_descriptor v_right = topo.right_vertex(e_right);
      topo.set_right_vertex(e_left, v_right);
      topo.set_left_edge(v_right, e_left);
    }
    else {
      topo.clear_right_vertex(e_left);
    }

    // Remove the now-redundant right edge and the vertex.
    topo.erase_edge(e_right);
    topo.erase_vertex(v);
  }
};

} // namespace Arrangement_on_curve_1
} // namespace CGAL

#endif
