// Copyright (c) 2026 Tel-Aviv University (Israel).
// All rights reserved.
// This file is part of CGAL (www.cgal.org).
// SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-Commercial
// Author(s): Efi Fogel         <efifogel@gmail.com>

#ifndef CGAL_ARRANGEMENT_ON_CURVE_1_ARRANGEMENT_ON_CURVE_1_H
#define CGAL_ARRANGEMENT_ON_CURVE_1_ARRANGEMENT_ON_CURVE_1_H

#include <CGAL/license/Arrangement_on_curve_1.h>

#include <variant>
#include <memory>

#include <CGAL/Arrangement_on_curve_1/Unbounded_topology_traits.h>

namespace CGAL {
namespace Arrangement_on_curve_1 {

/*! \class Arrangement_on_curve_1
 * \tparam GeometryTraits_1
 *
 * \tparam TopologyTraits
 *
 * \tparam BinarySearch when true (requires UseVector = true), the locate()
 *                      function in locate.h uses a binary search over the sorted
 *                      vertex vector, reducing locate from O(n) to O(log n).
 */
template <typename GeometryTraits_1,
          typename TopologyTraits = Unbounded_topology_traits<typename GeometryTraits_1::Point_1>,
          bool BinarySearch = false>
class Arrangement_on_curve_1 {
  static_assert(! BinarySearch || TopologyTraits::use_vector,
    "BinarySearch = true requires TopologyTraits::UseVector = true: binary search is only "
    "available over a random-access container.");

public:
  using Geometry_traits_1 = GeometryTraits_1;
  using Topology_traits = TopologyTraits;
  static constexpr bool binary_search_enabled = BinarySearch;

  // Define a clean type alias for the traits smart pointer
  using Shared_geometry_traits = std::shared_ptr<const Geometry_traits_1>;

  // Expose the allocator type from the topology traits so that callers can
  // query it via get_allocator() and use it with compatible containers.
  using Allocator_type = typename Topology_traits::Allocator_type;

  using Point_1 = typename Geometry_traits_1::Point_1;

  using Vertex_descriptor = typename Topology_traits::Vertex_descriptor;
  using Edge_descriptor = typename Topology_traits::Edge_descriptor;

  using Vertex_const_descriptor = typename Topology_traits::Vertex_const_descriptor;
  using Edge_const_descriptor = typename Topology_traits::Edge_const_descriptor;

  using Size = typename Topology_traits::Size;

  // Location result: a point is either ON a vertex or INSIDE an edge
  using Location_result = std::variant<Vertex_descriptor, Edge_descriptor>;
  using Const_location_result = std::variant<Vertex_const_descriptor, Edge_const_descriptor>;

private:
  Shared_geometry_traits m_geometry_traits;
  Topology_traits m_topology_traits;

public:
  // ==========================================================================
  // Special member functions.
  //
  // The destructor, move constructor, and move assignment are all correct as
  // generated by the compiler: shared_ptr and TopologyTraits both have correct
  // move semantics (std::list moves without invalidating iterators).
  //
  // The copy constructor and copy assignment must be explicitly defaulted here
  // (rather than left fully implicit) so that their correctness is visible and
  // intentional: they delegate entirely to TopologyTraits's copy operations,
  // which perform the non-trivial cross-reference patching needed to produce a
  // fully independent copy with valid internal iterators.
  // ==========================================================================
  ~Arrangement_on_curve_1() = default;

  Arrangement_on_curve_1(const Arrangement_on_curve_1&) = default;
  Arrangement_on_curve_1& operator=(const Arrangement_on_curve_1&) = default;

  Arrangement_on_curve_1(Arrangement_on_curve_1&&) noexcept = default;
  Arrangement_on_curve_1& operator=(Arrangement_on_curve_1&&) noexcept = default;

  // 1. Default constructor: allocates a default-constructed traits instance on the heap
  Arrangement_on_curve_1() :
    m_geometry_traits(std::make_shared<const Geometry_traits_1>()),
    m_topology_traits()
  {}

  // 2. Constructor passing an existing smart pointer
  Arrangement_on_curve_1(Shared_geometry_traits shared_geom_tr) :
    m_geometry_traits(std::move(shared_geom_tr)),
    m_topology_traits()
  { CGAL_assertion(m_geometry_traits != nullptr); }

  // 3. Fully custom constructor with topology traits
  Arrangement_on_curve_1(Shared_geometry_traits shared_geom_tr, Topology_traits topo_tr) :
    m_geometry_traits(std::move(shared_geom_tr)),
    m_topology_traits(std::move(topo_tr))
  { CGAL_assertion(m_geometry_traits != nullptr); }

  // 4. Allocator-aware constructor.
  // Constructs an empty arrangement whose internal topology traits (and
  // therefore its vertex/edge lists) use the supplied allocator.
  // Requires that TopologyTraits is constructible from an Allocator_type.
  Arrangement_on_curve_1(Shared_geometry_traits shared_geom_tr, const Allocator_type& alloc) :
    m_geometry_traits(std::move(shared_geom_tr)),
    m_topology_traits(alloc)
  { CGAL_assertion(m_geometry_traits != nullptr); }

  // ==========================================================================
  // MODIFIERS
  // ==========================================================================

  /*! creates a new vertex, enforcing the rightmost ordering invariant when BinarySearch is active.
   */
  Vertex_descriptor create_vertex(const Point_1& p) {
    if constexpr (binary_search_enabled) {
      // Enforce that new vertices are inserted strictly in left-to-right order.
      CGAL_assertion_msg(empty() ||
                         m_geometry_traits->compare_x_1_object()
                         (m_topology_traits.vertex_point(m_topology_traits.number_of_vertices() - 1), p) == CGAL::SMALLER,
        "When BinarySearch = true, vertices must be created in strictly increasing x-order.");
    }

    return m_topology_traits.create_vertex(p);
  }

  /*! creates an new edge.
   */
  Edge_descriptor create_edge() { return m_topology_traits.create_edge(); }

  /*! destroys a given vertex.
   */
  void destroy_vertex(Vertex_descriptor v) {
    if constexpr (binary_search_enabled) {
      // Enforce that only the rightmost vertex can be destroyed in O(1) time
      // without invalidating stored vertex indices in existing edges.
      CGAL_assertion_msg(v == this->topology_traits().number_of_vertices() - 1,
                         "When BinarySearch = true, only the rightmost vertex can be destroyed.");
    }

    this->topology_traits().erase_vertex(v);
  }

  /*! destroys a given edge.
   */
  void destroy_edge(Edge_descriptor e) { this->topology_traits().erase_edge(e); }

  /*! clears
   */
  void clear() { m_topology_traits.clear(); }

  void reset_shared_geometry_traits(Shared_geometry_traits new_shared_geom_tr) {
    // Safety check: changing traits on a populated structure is highly dangerous
    CGAL_precondition_msg(empty(), "Cannot reset the geometry traits pointer of a non-empty arrangement.");
    CGAL_assertion(new_shared_geom_tr != nullptr);
    m_geometry_traits = new_shared_geom_tr;
  }

  // ==========================================================================
  // ACCESSORS
  // ==========================================================================

  const Geometry_traits_1& geometry_traits_1() const { return *m_geometry_traits; }
  Shared_geometry_traits shared_geometry_traits_1() const { return m_geometry_traits; }

  const Topology_traits& topology_traits() const { return m_topology_traits; }
  Topology_traits& topology_traits() { return m_topology_traits; }

  bool empty() const { return m_topology_traits.empty(); }
  Size number_of_vertices() const { return m_topology_traits.number_of_vertices(); }
  Size number_of_edges() const { return m_topology_traits.number_of_edges(); }

  auto vertices() const { return m_topology_traits.vertices(); }
  auto edges() const { return m_topology_traits.edges(); }

  auto vertex_point_map() const { return m_topology_traits.vertex_point_map(); }
  auto vertex_data_map() const { return m_topology_traits.vertex_data_map(); }
  auto edge_data_map() const { return m_topology_traits.edge_data_map(); }

  Edge_descriptor unbounded_left_edge() { return m_topology_traits.unbounded_left_edge(); }
  Edge_const_descriptor unbounded_left_edge() const { return m_topology_traits.unbounded_left_edge(); }
  Edge_descriptor unbounded_right_edge() { return m_topology_traits.unbounded_right_edge(); }
  Edge_const_descriptor unbounded_right_edge() const { return m_topology_traits.unbounded_right_edge(); }

  Vertex_descriptor left_vertex(Edge_descriptor e) { return m_topology_traits.left_vertex(e); }
  Vertex_descriptor right_vertex(Edge_descriptor e) { return m_topology_traits.right_vertex(e); }
  Edge_descriptor left_edge(Vertex_descriptor v) { return m_topology_traits.left_edge(v); }
  Edge_descriptor right_edge(Vertex_descriptor v) { return m_topology_traits.right_edge(v); }

  Vertex_const_descriptor left_vertex(Edge_const_descriptor e) const { return m_topology_traits.left_vertex(e); }
  Vertex_const_descriptor right_vertex(Edge_const_descriptor e) const { return m_topology_traits.right_vertex(e); }
  Edge_const_descriptor left_edge(Vertex_const_descriptor v) const{ return m_topology_traits.left_edge(v); }
  Edge_const_descriptor right_edge(Vertex_const_descriptor v) const { return m_topology_traits.right_edge(v); }

  bool has_left_vertex(Edge_const_descriptor e) const { return m_topology_traits.has_left_vertex(e); }
  bool has_right_vertex(Edge_const_descriptor e) const { return m_topology_traits.has_right_vertex(e); }

  // obtains the allocator used by the internal topology traits.
  Allocator_type get_allocator() const noexcept { return m_topology_traits.get_allocator(); }

  // ============================================================================
  // HIGH-LEVEL TOPOLOGICAL OPERATIONS
  // ============================================================================

  /* inserts the very first point into an empty arrangement.
   * The single unbounded edge is split into (\f$(-\infty\f$, `v`) and (`v`, \f$(+\infty\f$).
   */
  Vertex_descriptor insert_empty(const Point_1& p) {
    auto& topo = m_topology_traits;

    // The arrangement must be empty: one unbounded edge exists.
    auto e_unbounded = topo.unbounded_left_edge();

    Vertex_descriptor v = topo.create_vertex(p);

    // Create the right new edge: (v, +inf)
    Edge_descriptor e_right = topo.create_edge();

    // Reuse e_unbounded as the left edge: (-inf, v)
    // It already has no left vertex; set its right vertex to v.
    topo.set_right_vertex(e_unbounded, v);

    // The right edge has v as its left vertex, and no right vertex.
    topo.set_left_vertex(e_right, v);

    // Wire the vertex to its two adjacent edges.
    topo.set_left_edge(v, e_unbounded);
    topo.set_right_edge(v, e_right);

    // Explicitly update the right boundary tracker.
    topo.set_unbounded_right_edge(e_right);

    return v;
  }

  /*! inserts a new point `p` strictly to the left of an existing vertex `v`.
   */
  Vertex_descriptor insert_before(Vertex_descriptor v, const Point_1& p) {
    if constexpr (binary_search_enabled) {
      CGAL_error_msg("insert_before() cannot be invoked when binary_search_enabled is true. "
                     "Vertices must be appended in strictly increasing x-order.");
    }

    Vertex_descriptor v_new = create_vertex(p);
    Edge_descriptor e_between = create_edge();

    Edge_descriptor e_left = m_topology_traits.left_edge(v);

    // Create a new edge to sit between v_new and v: (v_new, v)
    m_topology_traits.set_left_vertex(e_between, v_new);
    m_topology_traits.set_right_vertex(e_between, v);

    // The old left edge now terminates at v_new on its right
    m_topology_traits.set_right_vertex(e_left, v_new);

    // v_new sits between e_left and e_between.
    m_topology_traits.set_left_edge(v_new, e_left);
    m_topology_traits.set_right_edge(v_new, e_between);

    // v's left edge is now e_between.
    m_topology_traits.set_left_edge(v, e_between);

    return v_new;
  }

  /*! inserts a new point `p` strictly to the right of an existing vertex `v`.
   */
  Vertex_descriptor insert_after(Vertex_descriptor v, const Point_1& p) {
    if constexpr (binary_search_enabled) {
      // Enforce that v is the current rightmost vertex
      CGAL_assertion_msg(v == m_topology_traits.number_of_vertices() - 1,
                         "When BinarySearch = true, insert_after() can only be called on the rightmost vertex.");
    }

    Vertex_descriptor v_new = create_vertex(p);
    Edge_descriptor e_between = create_edge();

    Edge_descriptor e_right = m_topology_traits.right_edge(v);

    // Create a new edge to sit between v_new and v: (v_new, v)
    m_topology_traits.set_left_vertex(e_between, v);
    m_topology_traits.set_right_vertex(e_between, v_new);

    // The old right edge now starts from v_new
    m_topology_traits.set_left_vertex(e_right, v_new);

    // v_new is wired between e_between and e_right.
    m_topology_traits.set_left_edge(v_new, e_between);
    m_topology_traits.set_right_edge(v_new, e_right);

    // v's right edge is now e_between.
    m_topology_traits.set_right_edge(v, e_between);

    return v_new;
  }

  /*! splits the edge `e` by inserting a new point `p` inside it.
   * `e` becomes the left sub-edge; a new edge becomes the right sub-edge.
   */
  Vertex_descriptor split_edge(Edge_descriptor e, const Point_1& p) {
    if constexpr (binary_search_enabled) {
      // 1. Must split the rightmost unbounded edge (no right vertex)
      CGAL_assertion_msg(! m_topology_traits.has_right_vertex(e),
                         "When BinarySearch = true, split_edge() can only be called on the rightmost unbounded edge.");

      // 2. If e has a left vertex, it MUST be the current rightmost vertex in the vector.
      // (If e has no left vertex, it's the initial (-inf, +inf) edge of an empty arrangement.)
      CGAL_assertion_msg(! m_topology_traits.has_left_vertex(e) ||
                         m_topology_traits.left_vertex(e) == m_topology_traits.number_of_vertices() - 1,
                         "When BinarySearch = true, the edge being split must originate from the rightmost vertex.");
    }

    Vertex_descriptor v_new = create_vertex(p);
    Edge_descriptor e_right = create_edge();

    // If e has a right vertex, transfer it to e_right.
    if (m_topology_traits.has_right_vertex(e)) {
      Vertex_descriptor v_old_right = m_topology_traits.right_vertex(e);
      m_topology_traits.set_right_vertex(e_right, v_old_right);
      m_topology_traits.set_left_edge(v_old_right, e_right);
    }
    // e_right's left vertex is v_new.
    m_topology_traits.set_left_vertex(e_right, v_new);

    // e (the left sub-edge) now ends at v_new.
    m_topology_traits.set_right_vertex(e, v_new);

    // Wire v_new between e and e_right.
    m_topology_traits.set_left_edge(v_new, e);
    m_topology_traits.set_right_edge(v_new, e_right);

    return v_new;
  }

  /*! removes a vertex from the arrangement.
   * It merges its two adjacent edges into one, keeping the left edge and removing the right.
   */
  void remove(Vertex_descriptor v) {
    Edge_descriptor e_left = m_topology_traits.left_edge(v);
    Edge_descriptor e_right = m_topology_traits.right_edge(v);

    // Extend e_left to cover the span formerly covered by e_right.
    if (m_topology_traits.has_right_vertex(e_right)) {
      Vertex_descriptor v_right = m_topology_traits.right_vertex(e_right);
      m_topology_traits.set_right_vertex(e_left, v_right);
      m_topology_traits.set_left_edge(v_right, e_left);
    }
    else {
      m_topology_traits.clear_right_vertex(e_left);
    }

    // Destroy the now-redundant right edge and the vertex.
    destroy_edge(e_right);
    destroy_vertex(v);
  }

  // ==================================================================
  // BINARY SEARCH SUPPORT (only available / called when Topology_traits::UseVector = true)
  //
  // locate.h calls binary_search_vertex() when the topology traits has
  // BinarySearch = true (detected via the static constexpr below).
  //
  // The vertex vector is maintained in left-to-right sorted order by
  // Arrangement_on_curve_1's high-level insert operations.  We perform a
  // standard lower_bound-style search using the geometry traits' comparator.
  //
  // Returns:
  //   - the index of the matching vertex if p coincides with one, or
  //   - the index of the first vertex whose x-coordinate is > p, which is
  //     the right endpoint of the edge that contains p.
  //     (An out-of-range index equal to m_vertices.size() means p is to the
  //      right of all vertices, i.e. it lies in the rightmost edge.)
  //
  // The caller distinguishes the two cases by comparing the returned index
  // against m_vertices.size() and, if in range, by checking whether cmp
  // returns EQUAL for the vertex at that index.
  // ==================================================================
  template <typename Compare>
  std::size_t binary_search_vertex(const Point_1& p, Compare cmp) const {
    static_assert(Topology_traits::use_vector, "binary_search_vertex() is only available when use_vector = true.");

    const auto& vertices = m_topology_traits.raw_vertices();

    std::size_t lo = 0, hi = vertices.size();
    while (lo < hi) {
      std::size_t mid = lo + (hi - lo) / 2;
      auto res = cmp(vertices[mid].m_point, p);
      if (res == CGAL::SMALLER) lo = mid + 1;
      else if (res == CGAL::LARGER)  hi = mid;
      else return mid; // EQUAL — vertex found
    }
    // p is not at any vertex; lo is the index of the first vertex > p.
    return lo;
  }
};

} // namespace Arrangement_on_curve_1
} // namespace CGAL

#endif
