./data/
degenerate2.poly
degenerate0.poly
double_edge.poly
degenerate6.poly
degenerate5.poly
degenerate1.poly
degenerate0a.poly
triangle.poly
degenerate7.poly
degenerate3.poly
degenerate4.poly
degenerate13.poly
degenerate5a.poly
pseudo_split_10.poly
square.poly
rectangle.poly
pseudo_split_6.poly
equal_times_0.poly
pseudo_split_11.poly
degenerate9.poly
degenerate25.poly
degenerate12.poly
pseudo_split_0.poly
split_at_zero_0.poly
single_split.poly
degenerate27.poly
degenerate27c.poly
degenerate27b.poly
degenerate8.poly
degenerate11.poly
region_4.poly
degenerate10.poly
alley_0.poly
pseudo_split_2.poly
pseudo_split_1.poly
masked_double_split.poly
degenerate27d.poly
double_split.poly
closer_edge_event_1.poly
closer_edge_event_0.poly
star.poly
pseudo_split_4.poly
pseudo_split_3.poly
hole.poly
degenerate26.poly
multinode1.poly
multinode0.poly
pseudo_split_5.poly
near_degenerate_1.poly
degenerate_multinode0.poly
sample2.poly
degenerate22c.poly
parallels0_b.poly
parallels0.poly
degenerate28x.poly
pseudo_split_5b.poly
degenerate22b.poly
simple_3.poly
sample_3.poly
degenerate28a.poly
degenerate28aa.poly
pseudo_split_7.poly
simple_2.poly
sample_6.poly
degenerate28c.poly
alley_2.poly
sample.poly
simple_1.poly
sample_1.poly
alley_3.poly
pseudo_split_8.poly
pseudo_split_12.poly
degenerate22.poly
degenerate24.poly
simple_0.poly
sample_5.poly
pseudo_split_9.poly
degenerate20.poly
sample_0.poly
complex_0.poly
complex_1.poly
sample_2.poly
complex_2.poly
complex_3.poly
sample_4.poly
complex_4.poly
complex_5.poly
sample3.poly
many_holes.poly
sample_46.poly
sample_325.poly
sample_319.poly
sample_333.poly
sample_638.poly
sample_101.poly
sample_73.poly
sample_235.poly
sample_698.poly
sample_147.poly
degenerate21.poly
sample_298.poly
sample_85.poly
sample_102.poly
four_squares.poly
anchor.poly
complex_6.poly
