./data
sample_85.poly
sample_298.poly
sample_147.poly
sample_698.poly
sample_235.poly
sample_73.poly
sample_101.poly
sample_638.poly
sample_333.poly
sample_319.poly
sample_325.poly
sample_46.poly
sample_4.poly
sample_2.poly
sample_0.poly
vertex_event_9.poly
sample_5.poly
alley_3.poly
sample_1.poly
alley_2.poly
sample_6.poly
sample_3.poly
hole.poly
closer_edge_event_0.poly
closer_edge_event_1.poly
double_split.poly
masked_double_split.poly
alley_0.poly
alley_1.poly
region_4.poly
single_split.poly
vertex_event_0.poly
rectangle.poly
square.poly
triangle.poly
