./data
degenerate2.poly
degenerate0.poly
double_edge.poly
degenerate6.poly
degenerate5.poly
degenerate1.poly
triangle.poly
degenerate7.poly
degenerate3.poly
degenerate4.poly
square.poly
rectangle.poly
degenerate9.poly
degenerate12.poly
vertex_event_0.poly
split_at_zero_0.poly
single_split.poly
degenerate8.poly
region_4.poly
degenerate10.poly
alley_1.poly
alley_0.poly
masked_double_split.poly
double_split.poly
closer_edge_event_1.poly
closer_edge_event_0.poly
hole.poly
multinode1.poly
degenerate_multinode0.poly
parallels0_b.poly
parallels0.poly
sample_3.poly
sample_6.poly
alley_2.poly
sample_1.poly
alley_3.poly
sample_5.poly
vertex_event_9.poly
sample_0.poly
sample_2.poly
sample_4.poly
sample_46.poly
sample_325.poly
sample_319.poly
sample_333.poly
sample_638.poly
sample_101.poly
sample_73.poly
sample_235.poly
sample_698.poly
sample_147.poly
sample_298.poly
sample_85.poly
sample_102.poly
