#ifdef BENCH
#  define NDEBUG
#endif

#define CGAL_MESH_3_DEBUG_BEFORE_CONFLICTS     0
#define CGAL_MESH_3_DEBUG_AFTER_NO_INSERTION   0
#define CGAL_MESH_3_DEBUG_AFTER_INSERTION      0
#define CGAL_MESH_3_DEBUG_DOUBLE_MAP           0

// #define CGAL_MESHES_NO_OUTPUT

// #define CGAL_SURFACE_MESHER_EDGES_DEBUG_INTERSECTION
// #define CGAL_SURFACE_MESHER_DEBUG_POLYHEDRAL_SURFACE_CONSTRUCTION
// #define CGAL_SURFACE_MESHER_VERBOSE
// #define CGAL_POLYHEDRAL_SURFACE_VERBOSE_CONSTRUCTION
// #define CGAL_SURFACE_MESHER_EDGES_DEBUG_INSERTIONS
// #define CGAL_MESHES_DEBUG_REFINEMENT_POINTS
// #define CGAL_DEBUG_OCTREE_CONSTRUCTION

//#define CGAL_MESH_3_VERBOSE
//#define CGAL_MESH_3_IO_VERBOSE

// #define OPTIMIZE_INTERSECTION
