#!/bin/sh
exec ./implicit_surfaces_mesher_3 \
    \
    --inrimage ../../../Surface_mesher/examples/Surface_mesher/ImageIO/data/skull_2.9.inr.gz \
    --iso_value 2.9 \
    \
    --center_x 122 \
    --center_y 102 \
    --center_z 117 \
    --enclosing_sphere_radius 500 \
    \
    --number_of_initial_points 50 \
    \
    --radius_bound 5.2 \
    \
    --tets_aspect_ratio_bound 2 \
    --tets_size_bound 5 \
    \
    --initial_surface_off skull-surface-initiale.off \
    --surface_off skull-surface-after.off \
    \
    --mesh_after_filename skull-after.mesh \
    --slivers_off skull-slivers.off \
    \
    skull.mesh \
    \
    --read_initial_points dump_of_initial_points_of_skull \
    \
    --number_of_pump 0
