#!/bin/sh
exec ./implicit_surfaces_mesher_3 -f chair --number_of_initial_points 50 --radius_bound 0.1 --tets_aspect_ratio_bound 2 --tets_size_bound 0.01 --slivers_off chair-slivers.off --initial_surface_off chair-surface-initiale.off --mesh_after_filename chair-after.mesh chair.mesh --number_of_pump 0 --read_initial_points ./dump_of_initial_points_chair
