./data/agg_op/test01.txt
./data/agg_op/test02.txt
./data/agg_op/test03.txt
./data/agg_op/test04.txt
./data/agg_op/test05.txt
./data/agg_op/test06.txt
./data/agg_op/test07.txt
./data/agg_op/test08.txt
./data/agg_op/test09.txt
./data/agg_op/test10.txt
./data/agg_op/test11.txt
./data/agg_op/test12.txt
./data/agg_op/test13.txt
./data/agg_op/test14.txt
./data/agg_op/test15.txt
./data/agg_op/test16.txt
./data/agg_op/test17.txt
./data/agg_op/test18.txt
