#
# UseCGAL.cmake can be included in a project to load the needed compiler and linker
# settings to use CGAL.
#
# Use find_package(CGAL) or CMAKE_INSTALL_DIR/CMAKE_BINARY_DIR parameters to locate UseCGAL.cmake.
# If find_package(CGAL) is used, some of these settings will be already setup and appended here.
#
# DO NOT EDIT UseCGAL.cmake. It is generated by CMake from UseCGAL.cmake.in.
#

set(CMAKE_ALLOW_LOOSE_LOOP_CONSTRUCTS true)

if(NOT USE_CGAL_FILE_INCLUDED) 
  set(USE_CGAL_FILE_INCLUDED 1)

  include(CGALcommon)
  include(GeneratorSpecificSettings)
  
  #
  # The following variables are hard coded here at configuration time
  #
  set(CGAL_MAJOR_VERSION           "3")
  set(CGAL_MINOR_VERSION           "4")
  set(CGAL_BUILD_VERSION           "1")
  set(CGAL_BINARY_DIR              "C:/Work/CGAL-3.4-I-140")
  set(CGAL_INSTALL_DIR	           "C:/Program Files/CGAL/.")
  set(CGAL_LIB_INSTALL_DIR	       "C:/Program Files/CGAL/lib")
  set(CGAL_INCLUDE_INSTALL_DIR     "C:/Program Files/CGAL/include")
  set(CGAL_BIN_INSTALL_DIR	       "C:/Program Files/CGAL/")
  set(CGAL_AUXILIARY_INSTALL_DIR   "C:/Program Files/CGAL/auxiliary")
  set(CGAL_MODULE_INSTALL_DIR	     "C:/Program Files/CGAL/")
  set(CGAL_3RD_PARTY_INCLUDE_DIRS  "C:/Program Files/boost/boost_1_33_1;C:/Work/CGAL-3.4-I-140/auxiliary/gmp/include;C:/Work/CGAL-3.4-I-140/auxiliary/gmp/include;C:/Work/CGAL-3.4-I-140/include/CGAL/CORE")
  set(CGAL_3RD_PARTY_DEFINITIONS   "")
  set(CGAL_3RD_PARTY_LIBRARIES_DIR "")
  set(CGAL_3RD_PARTY_LIBRARIES     "")
  
  #
  # The following variables may have previous values comming from find_package(CGAL).
  # Hard-coded values at configuration time are appended here.
  #
  set(CGAL_INCLUDE_DIRS ${CGAL_INCLUDE_DIRS} "C:/Work/CGAL-3.4-I-140/include")
  set(CGAL_DEFINITIONS  ${CGAL_DEFINITIONS}  "-D_SECURE_SCL=0;-D_CRT_SECURE_NO_DEPRECATE;-DSCL_SECURE_NO_DEPRECATE")
  set(CGAL_LIBRARIES    ${CGAL_LIBRARIES}    "")
  
  set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CGAL_MODULE_INSTALL_DIR} ${CGAL_CMAKE_MODULE_PATH} )

  include_directories (${CGAL_INCLUDE_DIRS})
  include_directories (${CGAL_3RD_PARTY_INCLUDE_DIRS})

  add_definitions(${CGAL_DEFINITIONS})
  add_definitions(${CGAL_3RD_PARTY_DEFINITIONS})
  
  link_directories( ${CGAL_LIB_INSTALL_DIR} ${CGAL_3RD_PARTY_LIBRARIES_DIR} )
  
  set(CGAL_VERSION"${CGAL_MAJOR_VERSION}.${CGAL_MINOR_VERSION}.${CGAL_BUILD_VERSION}")
  
endif()
