#!/usr/local/bin/perl -swi
#
# ===========================================================================
#
# HTML postprocessing script -- cc_remove_unwanted_links
#
# $Revision$
# $Date$
#
# script to remove all links in text delimited by the comments
# <!-- REMOVE_LINKS_BEGIN --> and <!-- REMOVE_LINKS_END -->
# (each of which should be on its own line).
#
# Usage:  cc_remove_unwanted_links [file.html]
#
# ===========================================================================

$removeLinks = 0;

while (<>) {
   if ( m/<!-- REMOVE_LINKS_BEGIN -->/ ) {
      $removeLinks = 1;
   }
   elsif ( m/<!-- REMOVE_LINKS_END -->/ ) {
      $removeLinks = 0;
   }
   elsif ( $removeLinks ) {
     s/([^<]*)<A\s*HREF[^>]*>([^<]*)<\/A>/$1$2/g 
   }
   print; 
}
