#!/bin/sh

echo "Creating VC71 solution & project files..."

# NOTE: This is hard-coded
SCRIPTDIR="../../developer_scripts/examples"


# Creates a VC71 .vcproj file corresponding to a source file
# $1 is the source file
# $2 is the extension of the source file
#
create_project_file()
{
  srcfile=${1};
  ext=${2};
  
  # $srcname is a string of the form "source" were "source.some_extension" is the of the source file
  srcname=`echo $srcfile|sed -e "s/\.$ext//"`;
  
  # $projfile is a filename of the form "source.vcproj" were "source" is the basename of the source file
  projfile=`echo $srcfile|sed -e "s/\.$ext/\.vcproj/"`;
  
  # Creates a vcroj IFF it doesn't exist
  if [[ ! -e $projfile ]]; then

      GUID=`printf "%012d" $RANDOM`
  
      echo "Creating $projfile with GUID={00000000-0000-0000-0000-$GUID}"
  
      #
      # Takes a master .vcproj file, replaces the keywords 
      #   SOURCE for $srcname
      #   EXT    for $ext  
      # And moves the generated project file into the final folder
      #
      sed -e"s/SOURCE/$srcname/g"      $SCRIPTDIR/master.vcproj > ./src2sln_/temp.txt;
      sed -e"s/EXT/$ext/g"            ./src2sln_/temp.txt       > ./src2sln_/temp2.txt;
      sed -e"s/ZZZZZZZZZZZZ/$GUID/g"  ./src2sln_/temp2.txt      > $projfile
      
      rm -rf ./src2sln_/temp.txt
      rm -rf ./src2sln_/temp2.txt 
  fi
}


#
# Create a .vcproj Visual C++ makefile for each .C and .cpp file
# Usage: C2vcproj folder1 ...
#

# For each folder in parameters list
for h in $@ ; do
if [[ -d $h ]]; then
  cd $h;
  echo "In " $h;

  pkg=`basename $h`
  
  # ALWAYS create temporary subdirectory "src2sln_"
  if [[ -e src2sln_ ]]; then
    rm -r src2sln_;
  fi
  mkdir src2sln_;
  
  # For each .C and .cpp file file
  for ext in C cpp ; do
    for i in *.$ext ; do
      if [[ ! $i = "*.$ext" ]]; then
        # if $i contains a function "main()"
        zgrep main $i >/dev/null 2>&1
        if [[ $? == 0 ]]; then

          create_project_file $i $ext
          
        fi
      fi
    done
  done

  # Remove temporary subdirectory "src2sln_"
  rm -r src2sln_

  cd ..;
fi
done
