.PHONY: Surface_mesher_ref.doc Surface_mesher.doc

all: 
	cgal_manual Surface_mesher Surface_mesher_ref

Surface_mesher_ref.doc:
	cgal_manual Surface_mesher_ref

Surface_mesher.doc:
	cgal_manual Surface_mesher
