#ifndef SCENE_SEGMENTED_IMAGE_ITEM_CONFIG_H
#define SCENE_SEGMENTED_IMAGE_ITEM_CONFIG_H

#ifdef scene_segmented_image_item_EXPORTS
#  define SCENE_SEGMENTED_IMAGE_ITEM_EXPORT Q_DECL_EXPORT
#else
#  define SCENE_SEGMENTED_IMAGE_ITEM_EXPORT Q_DECL_IMPORT
#endif

#endif // SCENE_SEGMENTED_IMAGE_ITEM_CONFIG_H
