#ifndef SCENE_IMPLICIT_FUNCTION_ITEM_CONFIG_H
#define SCENE_IMPLICIT_FUNCTION_ITEM_CONFIG_H

#ifdef scene_implicit_function_item_EXPORTS
#  define SCENE_IMPLICIT_FUNCTION_ITEM_EXPORT Q_DECL_EXPORT
#else
#  define SCENE_IMPLICIT_FUNCTION_ITEM_EXPORT Q_DECL_IMPORT
#endif

#endif // SCENE_IMPLICIT_FUNCTION_ITEM_CONFIG_H
