#ifndef POINT_SET_ITEM_CONFIG_H
#define POINT_SET_ITEM_CONFIG_H

#ifdef point_set_EXPORTS
#  define POINT_SET_ITEM_EXPORT Q_DECL_EXPORT
#else
#  define POINT_SET_ITEM_EXPORT Q_DECL_IMPORT
#endif

#endif // POINT_SET_ITEM_CONFIG_H
