#ifndef SCENE_POLYHEDRON_ITEM_CONFIG_H
#define SCENE_POLYHEDRON_ITEM_CONFIG_H

#ifdef PS_demo_scene_polyhedron_item_EXPORTS
#  define SCENE_POLYHEDRON_ITEM_EXPORT Q_DECL_EXPORT
#else
#  define SCENE_POLYHEDRON_ITEM_EXPORT Q_DECL_IMPORT
#endif

#endif // SCENE_POLYHEDRON_ITEM_CONFIG_H
