//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Poisson.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_PoissonTYPE                 129
#define IDS_MESSAGE0                    130
#define IDD_DIALOG_OPTIONS              130
#define IDS_MESSAGE1                    131
#define IDS_MESSAGE2                    132
#define IDS_MESSAGE3                    133
#define IDC_EDIT_SM_ANGLE_APSS          1000
#define IDC_EDIT_SM_RADIUS_APSS         1001
#define IDC_EDIT_SM_DISTANCE_POISSON    1002
#define IDC_EDIT_DR_SHELL_SIZE          1003
#define IDC_EDIT_DR_SIZING              1004
#define IDC_EDIT_DR_MAXV                1005
#define IDC_EDIT_CONTOURING_VALUE       1006
#define IDC_EDIT_NB_NEIGHBORS_AVG_SPACING 1007
#define IDC_EDIT_MIN_CAMERAS_CONE_ANGLE 1008
#define IDC_EDIT_SM_ERROR_BOUND_APSS    1009
#define IDC_EDIT_AVG_KNN_SQ_DST_PERCENTAGE 1010
#define IDC_EDIT_SM_DISTANCE_APSS       1011
#define IDC_EDIT_LAMBDA                 1012
#define IDC_EDIT_CLUSTERING_STEP        1013
#define IDC_EDIT_RANDOM_SIMPLIFICATION_PERCENTAGE 1014
#define IDC_EDIT_SM_ANGLE_POISSON       1015
#define IDC_EDIT_SM_RADIUS_POISSON      1016
#define IDC_EDIT_NB_NEIGHBORS_PCA_NORMALS 1017
#define IDC_EDIT_NB_NEIGHBORS_OUTLIERS_REMOVAL 1018
#define IDC_EDIT_NB_NEIGHBORS_JET_FITTING_NORMALS 1019
#define IDC_EDIT_NB_NEIGHBORS_MST      1020
#define IDC_EDIT_SM_ERROR_BOUND_POISSON 1021
#define IDC_EDIT_NB_NEIGHBORS_APSS     1023
#define IDC_EDIT_NB_NEIGHBORS_SMOOTH_JET_FITTING 1025
#define ID_RENDER_POINTS                32771
#define ID_RENDER_NORMALS               32772
#define ID_RENDER_DELAUNAYEDGES         32773
#define ID_RECONSTRUCTION_DELAUNAYREFINEMENT 32774
#define ID_RECONSTRUCTION_POISSON       32776
#define ID_RENDER_CONTOUR               32777
#define ID_RECONSTRUCTION_POISSON_SURFACE_MESHING 32778
#define ID_ALGORITHMS_REFINEINSHELL     32781
#define ID_RENDER_ARCBALL               32789
#define ID_RENDER_SURFACE               32790
#define ID_EDIT_OPTIONS                 32793
#define ID_ARCBALL_RESET                32799
#define ID_ALGORITHMS_MARCHINGTETCONTOURING 32803
#define ID_FILE_SAVE_SURFACE            32805
#define ID_ALGORITHMS_ADVANCED          32806
#define ID_ALGORITHMS_POISSONSTATISTICS 32808
#define ID_ALGORITHMS_ESTIMATENORMALSBYPCA 32811
#define ID_ALGORITHMS_ESTIMATENORMALBYJETFITTING 32812
#define ID_ALGORITHMS_EXTRAPOLATENORMALS 32813
#define ID_ALGORITHMS_ORIENTNORMALSCAMERAS 32814
#define ID_ALGORITHMS_ORIENTNORMALSMST  32815
#define ID_ALGORITHMS_SMOOTHUSINGJETFITTING 32816
#define ID_CREATE_POISSON_TRIANGULATION 32818
#define ID_EDIT_MODE                    32819
#define ID_MODE_POINT_SET               32821
#define ID_MODE_POISSON                 32822
#define ID_ANALYSIS                     32824
#define ID_ALGORITHMS_OUTLIERS_REMOVAL_WRT_CAMERAS_CONE_ANGLE 32826
#define ID_ALGORITHMS_OUTLIERS_REMOVAL_WRT_AVG_KNN_SQ_DIST 32827
#define ID_ANALYSIS_AVERAGE_SPACING     32828
#define ID_ONE_STEP_POISSON_RECONSTRUCTION 32829
#define ID_RECONSTRUCTION_APSS_RECONSTRUCTION 32831
#define ID_MODE_APSS                    32832
#define ID_STEP_SOLVEPOISSONEQUATIONWITHNORMALIZEDDIVERGENCE 32834
#define ID_STEP_SOLVEPOISSONEQUATIONWITHNORMALIZEDDIVERGENCE32835 32835
#define ID_RECONSTRUCTION_POISSON_NORMALIZED 32836
#define ID_RECONSTRUCTION_ONE_STEP_NORMALIZED 32838
#define ID_RECONSTRUCTION_SAVEAS        32839
#define ID_STEP_CALCULATEAVERAGESPACING 32840
#define ID_STEP_EXTRAPOLATENORMALSUSINGGAUSSIANKERNELS 32841
#define ID_POINT_CLOUD_SIMPLIFICATION_BY_CLUSTERING 32844
#define ID_POINT_CLOUD_SIMPLIFICATION_RANDOM 32845
#define ID_EDIT_DELETE                  32867
#define ID_EDIT_RESET_SELECTION         32869
#define ID_RADIAL_NORMALS_ORIENTATION   32871
#define ID_FLIP_NORMALS                 32873

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32874
#define _APS_NEXT_CONTROL_VALUE         1026
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
