#!/bin/sh

./b2 -j2 -d+2 cxxflags=-D_HAS_ITERATOR_DEBUGGING=0 --stagedir=stage64 address-model=64 toolset=msvc-10.0 link=shared --with-thread --with-date_time --with-program_options --with-filesystem --with-system debug release stage
