cd examples\Alpha_shapes_2
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Alpha_shapes_3
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Arrangement_2
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Circulator
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Convex_hull_2
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Convex_hull_3
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Fixed_precision_nt
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Generator
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Getting_started
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Halfedge_DS
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Matrix_search
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Min_circle_2
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Min_ellipse
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Min_quadrilateral_2
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Min_sphere_d
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Nef_2
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Partition_2
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Planar_map
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Pm_with_intersections
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Point_set_2
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Polygon
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Polyhedron
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Polyhedron_IO
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
rem cd examples\RangeSegmentTrees
rem %MMAKE% clean
rem %MMAKE% all  
rem cd ..\.. 
cd examples\STL_Extension
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Topological_map
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Triangulation_2
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\Triangulation_3
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
cd examples\kdtrees
%MMAKE% clean
%MMAKE% all  
cd ..\.. 
