all:
	@for DIR in *; do \
	  if test "x$$DIR" != xGNUmakefile; then \
	    $(MAKE) -C $$DIR; \
	  fi; \
	done

clean:
	@for DIR in *; do \
	  if test "x$$DIR" != xGNUmakefile; then \
	    $(MAKE) -C $$DIR; \
	  fi; \
	done
