#!/bin/sh

dir=${PWD%/*}
dir=${dir##*/}

if [ "x${dir}" = "xdemo" ]; then
  in_demo="--no-run"
fi

[ ! -e CMakeLists.txt ] && echo "No CMakeLists.txt in current directory, creating it" && cgal_create_cmake_script test

# If there is already a cgal_test_with_cmake script in the current directory, execute it.
[ ! -x cgal_test_with_cmake ] && echo "No cgal_test_with_cmake in current directory, creating it" && create_cgal_test_with_cmake ${in_demo}

./cgal_test_with_cmake $@
cat error.txt
