include(${CGALCONFIGVERSIONFILE})
message("MAJOR_NUMBER=${CGAL_MAJOR_VERSION}
MINOR_NUMBER=${CGAL_MINOR_VERSION}
BUGFIX_NUMBER=${CGAL_BUGFIX_VERSION}
public_release_version=${CGAL_VERSION_PUBLIC_RELEASE_VERSION}
public_release_name=${CGAL_VERSION_PUBLIC_RELEASE_NAME}")
