#!/bin/sh

# Copyright (c) 2003,2005,2006  Utrecht University (The Netherlands),
# ETH Zurich (Switzerland),
# INRIA Sophia-Antipolis (France),
# Max-Planck-Institute Saarbruecken (Germany),
# and Tel-Aviv University (Israel).  All rights reserved.
#
# This file is part of CGAL (www.cgal.org)
#
# $URL$
# $Id$
# SPDX-License-Identifier: LGPL-3.0-or-later
#
# Author(s)     : 

TMPFILE="/tmp/cgal_find_includes"
rm -f ${TMPFILE}
touch ${TMPFILE}
find include/CGAL src -type f -exec grep '^ *# *include *<' {} \; >> ${TMPFILE}
find include/CGAL src -type f -exec grep '^ *# *include *"' {} \; >> ${TMPFILE}
grep -v 'CGAL/' ${TMPFILE}|grep -v 'LEDA/' |tr -d " "|sort|uniq
rm -f ${TMPFILE}

