#!/bin/sh

# Copyright (c) 2003,2005,2006  Utrecht University (The Netherlands),
# ETH Zurich (Switzerland),
# INRIA Sophia-Antipolis (France),
# Max-Planck-Institute Saarbruecken (Germany),
# and Tel-Aviv University (Israel).  All rights reserved.
#
# This file is part of CGAL (www.cgal.org); you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; version 3 of the License,
# or (at your option) any later version.
#
# Licensees holding a valid commercial license may use this file in
# accordance with the commercial license agreement provided with the software.
#
# This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
# WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
# $URL$
# $Id$
#
# Author(s)     : 

TMPFILE="/tmp/cgal_find_includes"
rm -f ${TMPFILE}
touch ${TMPFILE}
find include/CGAL src -type f -exec grep '^ *# *include *<' {} \; >> ${TMPFILE}
find include/CGAL src -type f -exec grep '^ *# *include *"' {} \; >> ${TMPFILE}
grep -v 'CGAL/' ${TMPFILE}|grep -v 'LEDA/' |tr -d " "|sort|uniq
rm -f ${TMPFILE}

