#!/bin/bash

: ${GITHUB_HUB:=$(which hub)}

if ! [ -x "${GITHUB_HUB}" ]; then
   echo 'Needs Github hub: https://github.com/github/hub and Github gh: https://github.com/cli/cli' >&2
   exit 1
fi

for pr in `gh pr list --label "Under Testing" | awk '{print $1}'`; do
    if ! hub merge https://github.com/CGAL/cgal/pull/$pr; then
        echo $pr;
        exit 1
    fi
done
