#!/bin/sh

if html2text -rcfile html2textrc changes.html > CHANGES; then
  sed -i -e '0,/===============================================================================/ d' CHANGES
  sed -i -e '0,/===============================================================================/ d' CHANGES
fi
exit # remove this line to test the generation of CHANGES.md
if pandoc changes.html -t markdown-raw_html-native_divs-native_spans -o CHANGES.md; then
  sed -i -e '0,/^------------------------------------------------------------------------$/ d' CHANGES.md
  sed -i -e '0,/^------------------------------------------------------------------------$/ d' CHANGES.md
fi    

