#!/bin/bash

export OPTIMIZATION_FLAGS="-O2 -DNDEBUG"
export KERNEL_FLAGS="-DCGAL_NEF3_USE_LEDA_INTEGER -DCGAL_NEF3_USE_HOMOGENEOUS -DCGAL_NEF3_UNION"

labrun -v --log Tetrahedra_and_grid -n tetrahedra_and_grid labmex -v --clean before ./tetrahedra_and_grid cube.nef3 2 2 2 123415

for (( i=3; $i<20; i=$i+1 )); do
  labrun -v --log Tetrahedra_and_grid ./tetrahedra_and_grid cube.nef3 $i $i $i 12345
done


