#ifndef LOCALLY_SHORTEST_PATH_ITEM_CONFIG_H
#define LOCALLY_SHORTEST_PATH_ITEM_CONFIG_H

#ifdef locally_shortest_path_item_EXPORTS
#  define LOCALLY_SHORTEST_PATH_ITEM_EXPORT Q_DECL_EXPORT
#else
#  define LOCALLY_SHORTEST_PATH_ITEM_EXPORT Q_DECL_IMPORT
#endif

#endif // LOCALLY_SHORTEST_PATH_ITEM_CONFIG_H
