s,^CGAL_INCL_DIR.*$,CGAL_INCL_DIR = /usr/include,
s,^CGAL_LIB_DIR.*$,CGAL_LIB_DIR = /usr/lib,
/^CGAL_INCL_CONF_DIR/,+1cCGAL_INCL_CONF_DIR = /usr/include
/-I$(CGAL_INCL_CONF_DIR)/d
/-I$(CGAL_INCL_DIR)/d
/-L$(CGAL_LIB_DIR)\/$(CGAL_OS_COMPILER)/d
s,CGAL_LIB_DESTINATION = '$(CGAL_LIB_DIR)/$(CGAL_OS_COMPILER)',CGAL_LIB_DESTINATION = '$(CGAL_LIB_DIR)',
