#!/bin/zsh

# old demos, to ignore
rm -rf Convex_hull_3_Demo
rm -rf Convex_hull_d_Demo
rm -rf GraphicsView_Demo
rm -rf Geomview_Demo
rm -rf Mesh_2_Demo
rm -rf Polyhedron_IO_Demo
rm -rf Interpolation_Demo
rm -rf Triangulation_3_Geomview_demos_Demo

# CGAL<=3.7
pushd AABB_tree_Demo;                   zip ../AABB_demo.zip          *    ;      popd
pushd Alpha_shapes_3_Demo;              zip ../alpha_shape_3.zip      *    ;      popd
pushd Bounding_volumes_Demo;            zip ../bounding_volumes_2.zip *    ;      popd
pushd Circular_kernel_2_Demo;           zip ../circular_kernel.zip    *    ;      popd
pushd Mesh_3_Demo;                      zip -r ../mesh_3.zip          *    ;      popd
pushd Periodic_3_triangulation_3_Demo;  zip ../periodic_3_triangulation_3.zip *;  popd
pushd Periodic_Lloyd_3_Demo;            zip ../periodic_3_lloyd.zip *;            popd
pushd Polygon_Demo;                     zip ../polygon.zip *               ;      popd
pushd Polyhedron_Demo;                  zip -r ../polyhedron_3.zip *       ;      popd
pushd Segment_Delaunay_graph_2_Demo;    zip ../segment_voronoi_diagram_2.zip *;   popd
pushd Surface_mesher_Demo;              zip ../surface_mesher.zip *;              popd
pushd Triangulation_2_Demo;
  zip ../regular_triangulation_2.zip Regular_triangulation_2.exe
  zip ../constrained_delaunay_triangulation_2.zip Constrained_Delaunay_triangulation_2.exe
  zip ../delaunay_triangulation_2.zip Delaunay_triangulation_2.exe
popd

# CGAL<3.8 but was forgot
pushd Principal_component_analysis_Demo;    zip ../pca.zip *; popd

# CGAL-3.8
pushd Largest_empty_rect_2_Demo;        zip ../largest_empty_rect_2.zip *;           popd
pushd Apollonius_graph_2_Demo;          zip ../apollonius_graph_2.zip *;             popd
pushd Stream_lines_2_Demo;              zip ../streamlines.zip *;                    popd
pushd Triangulation_3_Demo;             zip ../triangulation_3.zip *;                popd
#pushd Circular_kernel_3_Demo;           zip ../triangulation_3.zip *;                popd
pushd Alpha_shapes_2_Demo;              zip ../alpha_shapes_2.zip *;                 popd
pushd Generator_Demo;                   zip ../generator.zip *;                      popd
pushd L1_Voronoi_diagram_2_Demo;        zip ../l1_voronoi_diagram_2.zip *;           popd
pushd Snap_rounding_2_Demo;             zip ../snap_rounding_2.zip *;                popd
pushd Spatial_searching_2_Demo;         zip ../spatial_searching.zip *;              popd

# CGAL-4.0
pushd Linear_cell_complex_Demo;         zip ../linear_cell_complex_3.zip *;          popd

# CGAL-4.2 but was forgot -> published with 4.3
pushd Arrangement_on_surface_2_Demo;    zip ../arrangements_2.zip *;                 popd

# CGAL-4.5
pushd Periodic_2_triangulation_2_Demo;  zip ../Periodic_2_Delaunay_triangulation_2.zip *;
                                                                                     popd
# probably an error, in CGAL-4.5:
rm -rf Surface_mesh_deformation_Demo

# Demo not announced in the CGAL manual, from CGAL-3.8:
rm -rf Circular_kernel_3_Demo

# CGAL-4.6
pushd Polyline_simplification_2_Demo;   zip ../polyline_simplification_2.zip *; popd

# CGAL-4.7

pushd Segment_Delaunay_graph_Linf_2_Demo; zip ../segment_voronoi_diagram_2.zip *; popd

# check
echo CHECK now. The following lines should be empty.
for f in *zip; do unzip -qql $f; done | awk '{print $4}' >| done
for f in */**/*(.); do grep -qF ${f:t} done || ls $f; done
echo
