* Number-type: integer
* Description: Example with row rank less than m for removing an arificial variable and its equality constraint
* Generated-by: Generated by LP_Row_Rank_lt_m_QPE_solver.mw
NAME LP_Row_Rank_lt_m_QPE_solver
ROWS
 N obj
 E c1
 E c2
 E c3
COLUMNS
  x1  c1  3
  x1  c2  2
  x1  c3  1
  x1  obj  1
  x2  c1  4
  x2  c2  1
  x2  c3  2
  x2  obj  1
  x3  c1  2
  x3  c2  3
  x3  c3  0
  x3  obj  1
  x4  c1  5
  x4  c2  0
  x4  c3  3
  x4  obj  1
  x5  c1  1
  x5  c2  -1
  x5  c3  1
  x5  obj  1
RHS
  rhs  c1  6
  rhs  c2  -1
  rhs  c3  4
ENDATA
