#ifndef CGAL_PDB_BASIC_H
#define CGAL_PDB_BASIC_H
#include <CGAL/basic.h>

#define CGAL_PDB_BEGIN_NAMESPACE CGAL_BEGIN_NAMESPACE namespace PDB{
#define CGAL_PDB_END_NAMESPACE CGAL_END_NAMESPACE }
#define CGAL_PDB_NS CGAL::PDB

#define CGAL_PDB_BEGIN_INTERNAL_NAMESPACE CGAL_BEGIN_NAMESPACE namespace PDB_internal{
#define CGAL_PDB_END_INTERNAL_NAMESPACE CGAL_END_NAMESPACE }
#define CGAL_PDB_INTERNAL_NS CGAL::PDB_internal

#define CGAL_TNT_BEGIN_NAMESPACE CGAL_BEGIN_NAMESPACE namespace TNT {
#define CGAL_TNT_END_NAMESPACE CGAL_END_NAMESPACE }
#define CGAL_TNT_NS CGAL::TNT

#define CGAL_JAMA_BEGIN_NAMESPACE CGAL_BEGIN_NAMESPACE namespace JAMA {
#define CGAL_JAMA_END_NAMESPACE CGAL_END_NAMESPACE }
#define CGAL_JAMA_NS CGAL::JAMA


CGAL_BEGIN_NAMESPACE 
//! All exposed classes are put in this namespace.
namespace PDB {
}
CGAL_END_NAMESPACE


#endif
