${CGAL_DATA_DIR}/meshes/sphere.off data-coref/sphere-2.off ALL 1 1 1 1
data-coref/cube.off data-coref/coplanar_with_cube.off ALL 1 1 1 1
data-coref/cube.off data-coref/coplanar_with_cube1.off ALL 1 1 1 1
data-coref/cube.off data-coref/coplanar_with_cube2.off ALL 1 1 1 1
data-coref/cube.off data-coref/with_cube.off ALL 1 1 1 0
data-coref/open_large_cube.off data-coref/open_small_cube.off ALL 1 1 1 1
data-coref/open_large_cube.off data-coref/open_small_cube_inout.off ALL 0 0 0 0
${CGAL_DATA_DIR}/meshes/elephant.off data-coref/elephant_plane/plane_1.off ALL 1 1 1 1
${CGAL_DATA_DIR}/meshes/elephant.off data-coref/elephant_plane/plane_2.off ALL 1 1 1 1
${CGAL_DATA_DIR}/meshes/elephant.off data-coref/elephant_plane/plane_3.off ALL 1 1 1 1
data-coref/open_tet_1.off data-coref/open_tet_2.off ALL 1 1 1 1
data-coref/small_cube_coplanar_inside.off data-coref/small_cube_coplanar_outside.off ALL 1 1 1 1
data-coref/large_cube_coplanar.off data-coref/small_cube_coplanar_inside.off ALL 1 1 1 1
data-coref/large_cube_coplanar.off data-coref/small_cube_coplanar_outside.off ALL 1 1 1 1
data-coref/P7.off data-coref/Q7.off ALL 1 1 1 1
data-coref/square1.off data-coref/square2.off ALL 1 1 1 1
data-coref/square_pair.off data-coref/square2.off ALL 1 1 1 1
${CGAL_DATA_DIR}/meshes/elephant.off ${CGAL_DATA_DIR}/meshes/sphere.off ALL 1 1 1 1
data-coref/elephant_split_1.off data-coref/elephant_split_2.off ALL 1 1 1 1
data-coref/cube.off data-coref/cube_on_cube_edge.off ALL 0 1 1 1
data-coref/cube.off data-coref/cube_on_cube_corner.off ALL 1 1 1 1
data-coref/cow.off data-coref/cross.off ALL 1 1 1 1
${CGAL_DATA_DIR}/meshes/sphere.off data-coref/sphere_trans_cut.off ALL 0 0 0 0
data-coref/open_t11.off data-coref/open_t12.off ALL 1 1 1 1
data-coref/cube.off data-coref/coplanar_with_cube3.off ALL 1 1 1 1
data-coref/cube.off data-coref/coplanar_with_cube4.off ALL 1 1 1 1
data-coref/square1.off data-coref/square_pair.off ALL 1 1 1 1
data-coref/cube_meshed.off data-coref/cube.off ALL 1 1 1 1
data-coref/cube.off data-coref/cube_interior_tgt.off ALL 1 1 1 1
data-coref/cube.off data-coref/edge_tangent_to_cube.off ALL 1 1 0 1
data-coref/cube_dig.off data-coref/wedge.off ALL 1 1 1 1
