data-coref/sphere.off data-coref/elephant.off
data-coref/cow.off data-coref/cross.off
data-coref/broken_bound-1.off data-coref/broken_bound-2.off
data-coref/P7.off  data-coref/Q7.off
data-coref/testsuite/big_triangle.off data-coref/testsuite/sphere.off
data-coref/testsuite/big_triangle.off data-coref/testsuite/t3bis.off
data-coref/testsuite/big_triangle.off data-coref/testsuite/t3ter.off
data-coref/testsuite/big_triangle_barycenter.off  data-coref/testsuite/on_vertex_c.off
data-coref/testsuite/big_triangle_barycenter.off  data-coref/testsuite/on_edge_c.off
data-coref/testsuite/big_triangle_triangulated.off data-coref/testsuite/on_edge_c.off
data-coref/testsuite/c1.off data-coref/testsuite/c2.off
data-coref/testsuite/b1.off data-coref/testsuite/b2.off
data-coref/testsuite/d1.off data-coref/testsuite/d2.off
data-coref/testsuite/big_triangle.off data-coref/testsuite/ex1.off
data-coref/testsuite/big_triangle_barycenter.off  data-coref/testsuite/on_vertex.off
data-coref/testsuite/big_triangle_triangulated.off data-coref/testsuite/on_edge.off
data-coref/testsuite/1poly.off data-coref/testsuite/big_triangle.off
data-coref/testsuite/4poly.off data-coref/testsuite/big_triangle.off
data-coref/open_tet_1.off data-coref/open_tet_2.off
data-coref/coplanar_triangles/tr1-1.off data-coref/coplanar_triangles/tr1-2.off
data-coref/coplanar_triangles/tr2-1.off data-coref/coplanar_triangles/tr2-2.off
data-coref/coplanar_triangles/tr3-1.off data-coref/coplanar_triangles/tr3-2.off
data-coref/coplanar_triangles/tr4-1.off data-coref/coplanar_triangles/tr4-2.off
data-coref/elephant_split_1.off data-coref/elephant_split_2.off
data-coref/c1.off data-coref/c2.off
data-coref/c1.off data-coref/c2_bis.off
data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr1-1.off data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr1-2.off
data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr2-1.off data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr2-2.off
data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr3-1.off data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr3-2.off
data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr4-1.off data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr4-2.off
data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr5-1.off data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr6-1.off
data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr7-1.off data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr8-1.off
data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr5-2.off data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr6-2.off
data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr7-2.off data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr8-2.off
data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr9-1.off data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr9-2.off
data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr10-1.off data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr10-2.off
data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr11-1.off data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr11-2.off
data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr12-1.off data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr12-2.off
data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr13-1.off data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr13-2.off
data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr14-1.off data-coref/coplanar_triangles/all_cases/deg/collinear_edges/tr14-2.off
data-coref/coplanar_triangles/all_cases/deg/vertex_on_edge/tr1-1.off data-coref/coplanar_triangles/all_cases/deg/vertex_on_edge/tr1-2.off
data-coref/coplanar_triangles/all_cases/deg/vertex_on_edge/tr2-1.off data-coref/coplanar_triangles/all_cases/deg/vertex_on_edge/tr2-2.off
data-coref/coplanar_triangles/all_cases/deg/vertex_on_edge/tr3-1.off data-coref/coplanar_triangles/all_cases/deg/vertex_on_edge/tr3-2.off
data-coref/coplanar_triangles/all_cases/deg/vertex_on_edge/tr4-1.off data-coref/coplanar_triangles/all_cases/deg/vertex_on_edge/tr4-2.off
data-coref/coplanar_triangles/all_cases/deg/vertex_on_edge/tr5-1.off data-coref/coplanar_triangles/all_cases/deg/vertex_on_edge/tr5-2.off
data-coref/coplanar_triangles/all_cases/deg/vertex_on_edge/tr6-1.off data-coref/coplanar_triangles/all_cases/deg/vertex_on_edge/tr6-2.off
data-coref/coplanar_triangles/all_cases/deg/vertex_on_edge/tr7-1.off data-coref/coplanar_triangles/all_cases/deg/vertex_on_edge/tr7-2.off
data-coref/coplanar_triangles/all_cases/deg/vertex_on_edge/tr8-1.off data-coref/coplanar_triangles/all_cases/deg/vertex_on_edge/tr8-2.off
data-coref/coplanar_triangles/all_cases/deg/tr1-1.off data-coref/coplanar_triangles/all_cases/deg/tr1-2.off
data-coref/coplanar_triangles/all_cases/deg/tr2-1.off data-coref/coplanar_triangles/all_cases/deg/tr2-2.off
data-coref/coplanar_triangles/all_cases/deg/tr3-1.off data-coref/coplanar_triangles/all_cases/deg/tr3-2.off
data-coref/coplanar_triangles/all_cases/deg/tr4-1.off data-coref/coplanar_triangles/all_cases/deg/tr4-2.off
data-coref/coplanar_triangles/all_cases/deg/tr5-1.off data-coref/coplanar_triangles/all_cases/deg/tr5-2.off
data-coref/coplanar_triangles/all_cases/deg/tr6-1.off data-coref/coplanar_triangles/all_cases/deg/tr6-2.off
data-coref/coplanar_triangles/all_cases/deg/tr7-1.off data-coref/coplanar_triangles/all_cases/deg/tr7-2.off
data-coref/coplanar_triangles/all_cases/deg/tr8-1.off data-coref/coplanar_triangles/all_cases/deg/tr8-2.off
data-coref/coplanar_triangles/all_cases/deg/tr9-1.off data-coref/coplanar_triangles/all_cases/deg/tr9-2.off
data-coref/coplanar_triangles/all_cases/deg/tr10-1.off data-coref/coplanar_triangles/all_cases/deg/tr10-2.off
data-coref/coplanar_triangles/all_cases/deg/tr11-1.off data-coref/coplanar_triangles/all_cases/deg/tr11-2.off
data-coref/coplanar_triangles/all_cases/deg/tr12-1.off data-coref/coplanar_triangles/all_cases/deg/tr12-2.off
data-coref/coplanar_triangles/all_cases/deg/tr13-1.off data-coref/coplanar_triangles/all_cases/deg/tr13-2.off
data-coref/coplanar_triangles/all_cases/deg/tr14-1.off data-coref/coplanar_triangles/all_cases/deg/tr14-2.off
data-coref/coplanar_triangles/all_cases/deg/tr15-1.off data-coref/coplanar_triangles/all_cases/deg/tr15-2.off
data-coref/coplanar_triangles/all_cases/deg/tr16-1.off data-coref/coplanar_triangles/all_cases/deg/tr16-2.off
data-coref/coplanar_triangles/all_cases/deg/tr17-1.off data-coref/coplanar_triangles/all_cases/deg/tr17-2.off
data-coref/coplanar_triangles/all_cases/bugreport/tr1-1.off data-coref/coplanar_triangles/all_cases/bugreport/tr1-2.off
data-coref/coplanar_triangles/all_cases/bugreport/tr2-1.off data-coref/coplanar_triangles/all_cases/bugreport/tr2-2.off
data-coref/coplanar_triangles/all_cases/bugreport/tr3-1.off data-coref/coplanar_triangles/all_cases/bugreport/tr3-2.off
data-coref/coplanar_triangles/all_cases/tr1-1.off data-coref/coplanar_triangles/all_cases/tr1-2.off
data-coref/coplanar_triangles/all_cases/tr2-1.off data-coref/coplanar_triangles/all_cases/tr2-2.off
data-coref/coplanar_triangles/all_cases/tr3-1.off data-coref/coplanar_triangles/all_cases/tr3-2.off
data-coref/coplanar_triangles/all_cases/tr4-1.off data-coref/coplanar_triangles/all_cases/tr4-2.off
data-coref/coplanar_triangles/all_cases/tr5-1.off data-coref/coplanar_triangles/all_cases/tr5-2.off
data-coref/coplanar_triangles/all_cases/tr6-1.off data-coref/coplanar_triangles/all_cases/tr6-2.off
data-coref/coplanar_triangles/all_cases/tr7-1.off data-coref/coplanar_triangles/all_cases/tr7-2.off
data-coref/coplanar_triangles/all_cases/tr8-1.off data-coref/coplanar_triangles/all_cases/tr8-2.off
data-coref/coplanar_triangles/tr5-1.off data-coref/coplanar_triangles/tr5-2.off
data-coref/coplanar_triangles/tr6-1.off data-coref/coplanar_triangles/tr6-2.off
data-coref/coplanar_triangles/tr7-1.off data-coref/coplanar_triangles/tr7-2.off
data-coref/coplanar_triangles/tr8-1.off data-coref/coplanar_triangles/tr8-2.off
data-coref/coplanar_triangles/tr9-1.off data-coref/coplanar_triangles/tr9-2.off
data-coref/coplanar_triangles/simple/tr1-1.off data-coref/coplanar_triangles/simple/tr1-2.off
data-coref/coplanar_triangles/simple/tr2-1.off data-coref/coplanar_triangles/simple/tr2-2.off
data-coref/coplanar_triangles/simple/tr3-1.off data-coref/coplanar_triangles/simple/tr3-2.off
data-coref/coplanar_triangles/simple/tr4-1.off data-coref/coplanar_triangles/simple/tr4-2.off
data-coref/coplanar_triangles/simple/tr5-1.off data-coref/coplanar_triangles/simple/tr5-2.off
data-coref/coplanar_triangles/simple/tr6-1.off data-coref/coplanar_triangles/simple/tr6-2.off
data-coref/coplanar_triangles/simple/tr7-1.off data-coref/coplanar_triangles/simple/tr7-2.off
data-coref/coplanar_triangles/simple/tr8-1.off data-coref/coplanar_triangles/simple/tr8-2.off
data-coref/coplanar_triangles/tr10-1.off data-coref/coplanar_triangles/tr10-2.off
data-coref/coplanar_triangles/tr11-1.off data-coref/coplanar_triangles/tr11-2.off
data-coref/coplanar_triangles/tr12-1.off data-coref/coplanar_triangles/tr12-2.off
data-coref/coplanar_segments/tr1-1.off data-coref/coplanar_segments/tr1-2.off
data-coref/coplanar_segments/tr2-1.off data-coref/coplanar_segments/tr2-2.off
data-coref/coplanar_segments/tr3-2.off data-coref/coplanar_segments/tr3-1.off
data-coref/coplanar_segments/tr4-2.off data-coref/coplanar_segments/tr4-1.off
data-coref/coplanar_segments/tr5-2.off data-coref/coplanar_segments/tr5-1.off
data-coref/coplanar_segments/tr6-1.off data-coref/coplanar_segments/tr6-2.off
data-coref/intersection_edge/ex1-1.off data-coref/intersection_edge/ex1-2.off
data-coref/intersection_edge/ex2-1.off data-coref/intersection_edge/ex2-2.off
data-coref/intersection_vertex/ex1-1.off  data-coref/intersection_vertex/ex1-2.off
data-coref/intersection_vertex/ex2-1.off data-coref/intersection_vertex/ex2-2.off
data-coref/test_sets/t1.off data-coref/test_sets/t2.off
data-coref/big_triangle.off data-coref/elephant.off
