[main]
truncate_precision = 0.0000001
translate_and_scale_polyhedron = FALSE
merge_coplanar_faces = TRUE
coplanarity_epsilon = 0.0000001
perturbation_epsilon = 0.0000000001
stop_after_last_save_event = TRUE
check_degenerate_configuration = FALSE

[algo_3d_SimpleStraightSkel]
const_offset = 0
# available vertex_splitter: CombiVertexSplitter, ConvexVertexSplitter
vertex_splitter = CombiVertexSplitter
# available options for edge_event: convex, reflex, flip
edge_event = convex

[algo_3d_CombiVertexSplitter]
selected_combi = 0

[algo_3d_ConvexVertexSplitter]
optimization = max
