[Preprocessing]
truncate_precision = 0.0000001
translate_and_scale_polyhedron = FALSE
merge_coplanar_faces = TRUE
coplanarity_epsilon = 0.0000001
perturbation_epsilon = 0.0000000001
check_degenerate_configuration = FALSE

[Algorithm]
# CombiVertexSplitter, ConvexVertexSplitter
vertex_splitter = CombiVertexSplitter
selected_combinatorial_split = 0
convex_split_optimization = max
const_offset = 0
# convex, reflex, flip
edge_event = convex
stop_after_last_save_event = TRUE
