#!/bin/sh
CGALVER=3.2.1
cd $2/CGAL-$CGALVER
QTDIR=/Developer/qt
DYLD_LIBRARY_PATH=/Developer/qt/lib
export QTDIR DYLD_LIBRARY_PATH
if [ -e upgrade.cgal ]; then
  rm -f upgrade.cgal
  exit 0
fi
touch MacOSX-install.log
./install_cgal -ni --CXX /usr/bin/g++ >> $2/CGAL-$CGALVER/MacOSX-install.log
exit 0
