./data/test_construction/polylines/test01.txt
./data/test_construction/polylines/test02.txt
./data/test_construction/polylines/test03.txt
./data/test_construction/polylines/test04.txt
./data/test_construction/polylines/test05.txt
./data/test_construction/polylines/test06.txt
./data/test_construction/polylines/test07.txt
./data/test_construction/polylines/test08.txt
./data/test_construction/polylines/test09.txt
