./data/test_construction/test01.txt
./data/test_construction/test02.txt
./data/test_construction/test03.txt
./data/test_construction/test04.txt
./data/test_construction/test05.txt
./data/test_construction/test06.txt
./data/test_construction/test07.txt
./data/test_construction/test08.txt
./data/test_construction/test09.txt
./data/test_construction/test10.txt
./data/test_construction/test11.txt
./data/test_construction/test12.txt
./data/test_construction/test13.txt
./data/test_construction/test14.txt
./data/test_construction/test15.txt
./data/test_construction/test16.txt
./data/test_construction/test17.txt
./data/test_construction/test18.txt
./data/test_construction/test19.txt
./data/test_construction/test20.txt
./data/test_construction/test21.txt
./data/test_construction/test22.txt
./data/test_construction/test23.txt
./data/test_construction/test24.txt
./data/test_construction/test25.txt
./data/test_construction/test26.txt
./data/test_construction/test27.txt
./data/test_construction/test28.txt
./data/test_construction/test29.txt
./data/test_construction/test30.txt
./data/test_construction/test31.txt
./data/test_construction/test32.txt
./data/test_construction/test33.txt
./data/test_construction/test34.txt
./data/test_construction/test35.txt
./data/test_construction/test36.txt
./data/test_construction/test37.txt
./data/test_construction/test38.txt
./data/test_construction/test39.txt
./data/test_construction/test40.txt
./data/test_construction/test41.txt
./data/test_construction/test42.txt
./data/test_construction/test43.txt
./data/test_construction/test44.txt
./data/test_construction/test45.txt
./data/test_construction/test46.txt
./data/test_construction/test47.txt
