data/test_spherical_remove/test01.txt
data/test_spherical_remove/test02.txt
data/test_spherical_remove/test03.txt
data/test_spherical_remove/test04.txt
data/test_spherical_remove/test05.txt
data/test_spherical_remove/test06.txt
data/test_spherical_remove/test07.txt
data/test_spherical_remove/test08.txt
data/test_spherical_remove/test09.txt
data/test_spherical_remove/test10.txt
data/test_spherical_remove/test11.txt
data/test_spherical_remove/test12.txt
data/test_spherical_remove/test13.txt
data/test_spherical_remove/test14.txt
data/test_spherical_remove/test15.txt
data/test_spherical_remove/test16.txt
data/test_spherical_remove/test17.txt
data/test_spherical_remove/test18.txt
data/test_spherical_remove/test19.txt
