./data/test_construction/geodesic_arcs_on_sphere/test01.txt
./data/test_construction/geodesic_arcs_on_sphere/test02.txt
./data/test_construction/geodesic_arcs_on_sphere/test03.txt
./data/test_construction/geodesic_arcs_on_sphere/test04.txt
./data/test_construction/geodesic_arcs_on_sphere/test05.txt
./data/test_construction/geodesic_arcs_on_sphere/test06.txt
./data/test_construction/geodesic_arcs_on_sphere/test07.txt
./data/test_construction/geodesic_arcs_on_sphere/test08.txt
./data/test_construction/geodesic_arcs_on_sphere/test09.txt
./data/test_construction/geodesic_arcs_on_sphere/test10.txt
./data/test_construction/geodesic_arcs_on_sphere/test11.txt
./data/test_construction/geodesic_arcs_on_sphere/test12.txt
