./data/test_construction/segments/test01.txt
./data/test_construction/segments/test02.txt
./data/test_construction/segments/test03.txt
./data/test_construction/segments/test04.txt
./data/test_construction/segments/test05.txt
./data/test_construction/segments/test06.txt
./data/test_construction/segments/test07.txt
./data/test_construction/segments/test08.txt
./data/test_construction/segments/test09.txt
./data/test_construction/segments/test10.txt
./data/test_construction/segments/test11.txt
./data/test_construction/segments/test12.txt
./data/test_construction/segments/test13.txt
./data/test_construction/segments/test14.txt
./data/test_construction/segments/test15.txt
./data/test_construction/segments/test16.txt
./data/test_construction/segments/test17.txt
./data/test_construction/segments/test18.txt
./data/test_construction/segments/test19.txt
./data/test_construction/segments/test20.txt
./data/test_construction/segments/test21.txt
./data/test_construction/segments/test22.txt
./data/test_construction/segments/test23.txt
./data/test_construction/segments/test24.txt
./data/test_construction/segments/test25.txt
./data/test_construction/segments/test26.txt
./data/test_construction/segments/test27.txt
./data/test_construction/segments/test28.txt
./data/test_construction/segments/test29.txt
./data/test_construction/segments/test30.txt
./data/test_construction/segments/test31.txt
./data/test_construction/segments/test32.txt
./data/test_construction/segments/test33.txt
./data/test_construction/segments/test34.txt
./data/test_construction/segments/test35.txt
./data/test_construction/segments/test36.txt
./data/test_construction/segments/test37.txt
./data/test_construction/segments/test38.txt
./data/test_construction/segments/test39.txt
./data/test_construction/segments/test40.txt
./data/test_construction/segments/test41.txt
./data/test_construction/segments/test42.txt
./data/test_construction/segments/test43.txt
./data/test_construction/segments/test44.txt
./data/test_construction/segments/test45.txt
./data/test_construction/segments/test46.txt
./data/test_construction/segments/test47.txt
./data/test_construction/segments/test48.txt
./data/test_construction/segments/test49.txt
./data/test_construction/segments/test50.txt
