./data/spheres/stest.cin
./data/spheres/stest2.cin
./data/spheres/stest3.cin
./data/spheres/stest4.cin
./data/spheres/stest5.cin
./data/spheres/stest7.cin
./data/spheres/stest8.cin
./data/spheres/stest9.cin
./data/spheres/stest10.cin
./data/spheres/stest11.cin
./data/spheres/stest12.cin
./data/spheres/stest13.cin
./data/spheres/stest14.cin
./data/spheres/stest15.cin
./data/spheres/stest16.cin
./data/spheres/stest17.cin
./data/spheres/stest18.cin
./data/spheres/stest19.cin
./data/spheres/stest20.cin
./data/spheres/stest21.cin
./data/spheres/stest22.cin
./data/spheres/stest23.cin

