./data/triangles/test.cin
./data/triangles/test2.cin
./data/triangles/test3.cin
./data/triangles/test4.cin
./data/triangles/test5.cin
./data/triangles/test6.cin
./data/triangles/test7.cin
./data/triangles/test8.cin
./data/triangles/test9.cin
./data/triangles/test10.cin
./data/triangles/test11.cin
./data/triangles/test12.cin
./data/test_w_overlap.cin
./data/test_w_vertical.cin
./data/holes.cin
./data/test_random.cin
./data/test_slow.cin
./data/test_isolated.cin
./data/test_isolated2.cin
./data/triangles/grid_inter_tri_const_envelope.cin
./data/triangles/grid_intersecting_triangles.cin
./data/triangles/grid_no_inter_6.cin
./data/triangles/test_random2.cin
./data/triangles/osnat/osnat_4_24.dat
./data/triangles/osnat/osnat_5_40.dat
./data/triangles/random_10.in
./data/triangles/random_20.in
./data/triangles/random_30.in
./data/triangles/random_40.in
./data/triangles/grid_inter_tri_const_envelope_40.cin
./data/triangles/random_50.in
./data/triangles/random_50_small_0.5.in
./data/triangles/random_50_small_1.in

