#ifndef CGAL_ICONS_H
#define CGAL_ICONS_H


/* XPM */
static char *zoomin_xpm[] = {
/* columns rows colors chars-per-pixel */
"32 32 5 1",
"  c black",
". c #808080",
"X c #c0c0c0",
"o c white",
"O c None",
/* pixels */
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOO       XXOOOOOOOOOOOOO",
"OOOOOOOX  OOOOOOX  XOOOOOOOOOOOO",
"OOOOOOX OOOOOOOOOOX XOOOOOOOOOOO",
"OOOOOX OOOOOOOOOOOOX XOOOOOOOOOO",
"OOOOX OOOOOOOOOOOOOOX XOOOOOOOOO",
"OOOO XOOOOOOO  OOOOOOX OOOOOOOOO",
"OOOO OOOOOOOO  OOOOOOO OOOOOOOOO",
"OOO .OOOOOOOO  OOOOOOOX OOOOOOOO",
"OOO OOOOOOOOO  OOOOOOOO OOOOOOOO",
"OOO OOOOO          OOOO OOOOOOOO",
"OO. OOOOO          OOOO OOOOOOOO",
"OO. OOOOOOOOO  OOOOOOOO OOOOOOOO",
"OO. OOOOOOOOO  OOOOOOOO OOOOOOOO",
"OOO. OOOOOOOO  OOOOOOOO OOOOOOOO",
"OOO. .OOOOOOO  OOOOOO.  OOOOOOOO",
"OOOO. OOOOOOOOOOOOOOO   OOOOOOOO",
"OOOO.. OOOOOOOOOOOOO  o  OOOOOOO",
"OOOOO.. OOOOOOOOOOO    o  OOOOOO",
"OOOOOO..  OOOOOOX       oX OOOOO",
"OOOOOOO...       X..   XXoX OOOO",
"OOOOOOOOO.......OO... XXXXoX OOO",
"OOOOOOOOOOOOOOOOOOO... XXXXoX OO",
"OOOOOOOOOOOOOOOOOOOO... XXXXo  O",
"OOOOOOOOOOOOOOOOOOOOO... XX    O",
"OOOOOOOOOOOOOOOOOOOOOO...     OO",
"OOOOOOOOOOOOOOOOOOOOOOO...   OOO",
"OOOOOOOOOOOOOOOOOOOOOOOO..OOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO"
};
/* XPM */
static char *zoomout_xpm[] = {
/* columns rows colors chars-per-pixel */
"32 32 5 1",
"  c black",
". c #808080",
"X c #c0c0c0",
"o c white",
"O c None",
/* pixels */
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOO       XXOOOOOOOOOOOOO",
"OOOOOOOX  OOOOOOX  XOOOOOOOOOOOO",
"OOOOOOX OOOOOOOOOOX XOOOOOOOOOOO",
"OOOOOX OOOOOOOOOOOOX XOOOOOOOOOO",
"OOOOX OOOOOOOOOOOOOOX XOOOOOOOOO",
"OOOO XOOOOOOOOOOOOOOOX OOOOOOOOO",
"OOOO OOOOOOOOOOOOOOOOO OOOOOOOOO",
"OOO .OOOOOOOOOOOOOOOOOX OOOOOOOO",
"OOO OOOOOOOOOOOOOOOOOOO OOOOOOOO",
"OOO OOOOO         OOOOO OOOOOOOO",
"OO. OOOOO         OOOOO OOOOOOOO",
"OO. OOOOOOOOOOOOOOOOOOO OOOOOOOO",
"OO. OOOOOOOOOOOOOOOOOOO OOOOOOOO",
"OOO. OOOOOOOOOOOOOOOOOO OOOOOOOO",
"OOO. .OOOOOOOOOOOOOOO.  OOOOOOOO",
"OOOO. OOOOOOOOOOOOOOO   OOOOOOOO",
"OOOO.. OOOOOOOOOOOOO  o  OOOOOOO",
"OOOOO.. OOOOOOOOOOO    o  OOOOOO",
"OOOOOO..  OOOOOOX       oX OOOOO",
"OOOOOOO...       X..   XXoX OOOO",
"OOOOOOOOO.......OO... XXXXoX OOO",
"OOOOOOOOOOOOOOOOOOO... XXXXoX OO",
"OOOOOOOOOOOOOOOOOOOO... XXXXo  O",
"OOOOOOOOOOOOOOOOOOOOO... XX    O",
"OOOOOOOOOOOOOOOOOOOOOO...     OO",
"OOOOOOOOOOOOOOOOOOOOOOO...   OOO",
"OOOOOOOOOOOOOOOOOOOOOOOO..OOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO"
};
/* XPM */
static char *zoomin_reg_xpm[] = {
/* columns rows colors chars-per-pixel */
"32 32 6 1",
"  c black",
". c magenta",
"X c #808080",
"o c #c0c0c0",
"O c white",
"+ c None",
/* pixels */
"++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++",
"+++++++++       oo++++++++++++++",
"++++++o  ++++++o  o+++++++++++++",
"+++++o ++++++++++o o++++++++++++",
"++++o ++++++++++++o o+++++++++++",
"+++o ++++++++++++++o o++++++++++",
"+++ o+++++++++++++++o ++++++++++",
"+++ +++++++++++++++++ ++++++++++",
"++ X+++++++++++++++++o +++++++++",
"++                ++++ +++++++++",
"++  ............. ++++ +++++++++",
"+X  ............. ++++ +++++++++",
"+X  ............. ++++ +++++++++",
"+X  ............. ++++ +++++++++",
"++X ............. ++++ +++++++++",
"++X X............ ++X  +++++++++",
"+++X ............ ++   +++++++++",
"+++XX ........... +  O  ++++++++",
"+++ XX ..........     O  +++++++",
"+++ .XX  ......o       Oo ++++++",
"+++ ..XXX       oXX   ooOo +++++",
"+++ ....XXXXXXX..XXX ooooOo ++++",
"+++ ............. XXX ooooOo +++",
"+++ ............. +XXX ooooO  ++",
"+++ ............. ++XXX oo    ++",
"+++ ............. +++XXX     +++",
"+++               ++++XXX   ++++",
"+++++++++++++++++++++++XX+++++++",
"++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++"
};
/* XPM */
static char *voronoi_xpm[] = {
/* columns rows colors chars-per-pixel */
"32 32 3 1",
"  c black",
". c red",
"X c None",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXX",
"XXXXXXXXXXXXX  XXXXXXX.XXXXXXXXX",
"XXXXXXXXXXXX     XXXX.XXXXXXXXXX",
".XXXXXXXXXXX  X    X..XXXXXXXXXX",
"..XXXXXXXXX X XXX   .XXXXXXXXXXX",
"X..XXXXXXX  X XXXXX.. XXXXXXXXXX",
"XX..XXXXXX XX XXXX..X   XXXXXXXX",
"XXX...XXX XXX XXXX..XXX  XXXXXXX",
"XXXX...X  XXX XXX..XXXX XXXXXXXX",
"XXXXXX.. XXXX XXX..XXXX XXXXXXXX",
"XXXXXXX..XXXX XX..XXXX XXXXXXXXX",
"XXXXXX  ..........XXX XXXXXXXXXX",
"XXXXX  XX..........X  XXXXXXXXXX",
"XXXXX XXX..XX XXXX.. XXXXXXXXXXX",
"XXXX  XXX.XXX XXXXX...XXXXXXXXXX",
"XXXX  XX..XXX XXXX  ...XXXXXXXXX",
"XXXXX  ..XXXX XXX  XXX..XXXXXXXX",
"XXXXXX . XXXX XXX XXXXX..XXXXXXX",
"XXXXXX..  XXX XX  XXXXXX..XXXXXX",
"XXXXXX.XX   X X  XXXXXXXX..XXXXX",
"XXXXX.XXXX      XXXXXXXXXX..XXXX",
"XXXX..XXXXXX    XXXXXXXXXXX...XX",
"XXXX.XXXXXXXX  XXXXXXXXXXXXX...X",
"XXX.XXXXXXXXXXXXXXXXXXXXXXXXXX..",
"XX..XXXXXXXXXXXXXXXXXXXXXXXXXXX.",
"XX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};

/* XPM */
static char *line_xpm[] = {
/* columns rows colors chars-per-pixel */
"32 32 2 1",
"  c black",
". c None",
/* pixels */
"................................",
"................................",
"................................",
"................................",
"................................",
"....... ........................",
"......   .......................",
".......   ......................",
"........   .....................",
".........   ....................",
"..........   ...................",
"...........   ..................",
"............   .................",
".............   ................",
"..............   ...............",
"...............   ..............",
"................   .............",
".................   ............",
"..................   ...........",
"...................   ..........",
"....................   .........",
".....................   ........",
"......................   .......",
"....................... ........",
"................................",
"................................",
"................................",
"................................",
"................................",
"................................",
"................................",
"................................"
};
/* XPM */
static char *point_xpm[] = {
/* columns rows colors chars-per-pixel */
"32 32 3 1",
"  c black",
". c green",
"X c None",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXX",
"XXXXXXXXX     ..     XXXXXXXXXXX",
"XXXXXXXXX     ..     XXXXXXXXXXX",
"XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};
/* XPM */
static char *notool_xpm[] = {
/* columns rows colors chars-per-pixel */
"32 32 3 1",
"  c black",
". c red",
"X c None",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXX..........XXXXXXXXXXX",
"XXXXXXXXXX............XXXXXXXXXX",
"XXXXXXXX................XXXXXXXX",
"XXXXXXX.....XXXXXXXX.....XXXXXXX",
"XXXXXXX....XXXXXXXX......XXXXXXX",
"XXXXXX....XXXXXXXX........XXXXXX",
"XXXXX....XXXXXXXX....XX....XXXXX",
"XXXXX...XXXXXXXX....XXXX...XXXXX",
"XXXXX...XXXXXXX....XXXXX...XXXXX",
"XXXXX...XXXXXX....XXXXXX...XXXXX",
"XXXXX...XXXXX....XXXXXXX...XXXXX",
"XXXXX...XXXX....XXXXXXXX...XXXXX",
"XXXXX...XXX....XXXXXXXXX...XXXXX",
"XXXXX...XX....XXXXXXXXXX...XXXXX",
"XXXXX........XXXXXXXXXX....XXXXX",
"XXXXXX......XXXXXXXXXX....XXXXXX",
"XXXXXXX....XXXXXXXXXX....XXXXXXX",
"XXXXXXX.....XXXXXXXX.....XXXXXXX",
"XXXXXXXX................XXXXXXXX",
"XXXXXXXXXX............XXXXXXXXXX",
"XXXXXXXXXXX..........XXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};
/* XPM */
static char *zoomin_rect_xpm[] = {
/* columns rows colors chars-per-pixel */
"32 32 2 1",
"  c black",
". c None",
/* pixels */
"................................",
"................................",
"................................",
"................................",
"..                            ..",
"..                            ..",
".. .......................... ..",
".. .......................... ..",
".. .                        . ..",
".. .  ....................  . ..",
".. .  ....................  . ..",
".. .  ...              ...  . ..",
".. .  ...              ...  . ..",
".. .  ...  ..........  ...  . ..",
".. .  ...  ..........  ...  . ..",
".. .  ...  ..........  ...  . ..",
".. .  ...  ..........  ...  . ..",
".. .  ...              ...  . ..",
".. .  ...              ...  . ..",
".. .  ....................  . ..",
".. .  ....................  . ..",
".. .  ....................  . ..",
".. .                        . ..",
".. .......................... ..",
".. .......................... ..",
"..                            ..",
"..                            ..",
"................................",
"................................",
"................................",
"................................",
"................................"
};
/* XPM */
static char *nearest_vertex_xpm[] = {
/* columns rows colors chars-per-pixel */
"32 32 3 1",
"  c black",
". c red",
"X c None",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX  XXXXXXXXXXXXXXX",
"XXXX               XXXXXXXXXXXXX",
"XXX                  XXXXXXXXXXX",
"XXX     XXXXXXX  X    XXXXXXXXXX",
"XXX         XXX  XXX    XXXXXXXX",
"XXX  XXX         XXXX     XXXXXX",
"XXX  XXXXXXX               XXXXX",
"XXX  XXXXXXXXX XX         XXXXXX",
"XXX  XXXXXXXX  XX  XXXXX  XXXXXX",
"XXX  XXXXXXX  XXXX  XXXX  XXXXXX",
"XXX  XXXXXXX XXXXXX XXXX  XXXXXX",
"XXX  XXXXXX  XXXXXX  XXX  XXXXXX",
"XXX  XXXXXX XXXXXXXX XXX  XXXXXX",
"XXX  XXXXX  XXXXXXXX  XX  XXXXXX",
"XXX  XXXXX XXXXXXXXXX XX  XXXXXX",
"XXX  XXXX  XXXXXXXXXX  X  XXXXXX",
"XXX  XXXX XXXXXXXXXXXX X  XXXXXX",
"XXX ...X  XXXXXXXXXXXX    XXXXXX",
"XXX..... XXXXXXXXXXXXXX   XXXXXX",
"XX.......XXXXXXXXXXXXXXX  XXXXXX",
"XX.......XXXXXXXXXXXXXXX  XXXXXX",
"XX.......                 XXXXXX",
"XXX.....                  XXXXXX",
"XXXX...XXXXXXXXXXXXXXXXXX XXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};

/* XPM */
static char *triangulation_xpm[] = {
/* columns rows colors chars-per-pixel */
"32 32 3 1",
"  c black",
". c navy",
"X c None",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXX.............XXXXXXXXX",
"XXXXXXXXX..XXXXXXXXXX...XXXXXXXX",
"XXXXXXXXX.X.XXXXXXXX.X.X.XXXXXXX",
"XXXXXXXX.XX.XXXXXXX.X.XX.XXXXXXX",
"XXXXXXXX.XXX.XXXXX.XX.XXX.XXXXXX",
"XXXXXXXX.XXX.XXXX.XXX.XXXX.XXXXX",
"XXXXXXX.XXXXX.XX.XXXX.XXXXX.XXXX",
"XXXXXXX.XXXXXX..XXXX.XXXX...XXXX",
"XXXXXX.XXXXXXX...XXX.XX..X..XXXX",
"XXXXXX.XXXXX....X......XX.X.XXXX",
"XXXXXX.XXXX.X.X.XXXX.XXXX.X.XXXX",
"XXXXX.XXX..XX.XX.XXX.XXX.XX.XXXX",
"XXXXX.XX.XXXX.XX.XXX.XXX.XXX.XXX",
"XXXXX...XXXXX.XXX.XX.XX.XXXX.XXX",
"XXXX..XXXXXX.XXXXX.X.XX.XXXX.XXX",
"XXXX...XXXXX.XXXXX.X.X.XXXXX.XXX",
"XXXX.XX......XXXXXX..X.XXXXX.XXX",
"XXXX.XXXXXXX.....XX..........XXX",
"XXXX.XXXXX..X.XXX.....XXXX.XXXXX",
"XXXX.XXXX.XXXX.XXXXXX.XXX.XXXXXX",
"XXXX.XXX.XXXXXX.XXXXX.XX.XXXXXXX",
"XXXX.X..XXXXXXXX.XXX.XX.XXXXXXXX",
"XXXX..XXXXXXXXXXX.XX.XX.XXXXXXXX",
"XXXX.....XXXXXXXXX.X.X.XXXXXXXXX",
"XXXXXXXXX........XX...XXXXXXXXXX",
"XXXXXXXXXXXXXXXXX....XXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};

/* XPM */
static char *movepoint_xpm[] = {
/* columns rows colors chars-per-pixel */
"32 32 3 1",
"  c black",
". c red",
"X c None",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXX   XXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXX   XXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXX  XXXXXXX...XXXXXXXX  XXXXX",
"XXXX        XX...XX         XXXX",
"XXXXX  XXXXXXX...XXXXXXXX  XXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXX   XXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXX   XXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};
/* XPM */
static char *points_xpm[] = {
/* columns rows colors chars-per-pixel */
"32 32 2 1",
"  c black",
". c None",
/* pixels */
"................................",
".  ......  ..................  .",
".  ......  ..................  .",
"................................",
"................................",
".......................  .......",
".......  ......  ......  .......",
".......  ......  ...............",
"................................",
"................................",
".........  .....................",
".........  ...............  ....",
"....  ..........  ........  ....",
"....  ..........  ..............",
"................................",
"........  ...........  .........",
"........  ...........  .........",
"................................",
"............................  ..",
".....  .........  ..........  ..",
".....  .........  ..............",
"................................",
"................................",
"..........  ....................",
"..........  ............  ......",
"....................  ..  ......",
"....................  ..........",
"................................",
"................................",
".  ............  ............  .",
".  ............  ............  .",
"................................"
};

/* XPM */
static char *handtool_xpm[] = {
/* columns rows colors chars-per-pixel */
"32 32 3 1",
"  c black",
". c red",
"X c None",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XX  XXXXXXXXXXXXXXXXXXXXXX   XXX",
"XX     XXXXXXXXXXXXXXXX     XXXX",
"XXX  XXXXXXXXXXXXXXXXXXXX   XXXX",
"XXX X XXXXXXXXXXXXXXXXXX X XXXXX",
"XXXXXX XXXXXXXXXXXXXXX  XX XXXXX",
"XXXXXXX  XXXXXXXXXXXX XXXXXXXXXX",
"XXXXXXXXX XXXXXXXXX  XXXXXXXXXXX",
"XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX",
"XXXXXXXXXXX X..X. XXXXXXXXXXXXXX",
"XXXXXXXXXXXX.... XXXXXXXXXXXXXXX",
"XXXXXXXXXXX.......XXXXXXXXXXXXXX",
"XXXXXXXXXXXX....XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXX.....XXXXXXXXXXXXXXX",
"XXXXXXXXXXX. .XX. XXXXXXXXXXXXXX",
"XXXXXXXXXXX XXXXXX XXXXXXXXXXXXX",
"XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX",
"XXXXXXXXX XXXXXXXXXX XXXXXXXXXXX",
"XXXXXXXXX XXXXXXXXXX XXXXXXXXXXX",
"XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX",
"XXXXXXX XXXXXXXXXXXXXX XXXXXXXXX",
"XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX",
"XXXXXX XXXXXXXXXXXXXXXXX XX XXXX",
"XXXXX XXXXXXXXXXXXXXXXXXX   XXXX",
"XX X XXXXXXXXXXXXXXXXXX     XXXX",
"XX  XXXXXXXXXXXXXXXXXXXXX   XXXX",
"XX    XXXXXXXXXXXXXXXXXXXXXXXXXX",
"XX  XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};
/* XPM */
static char *mouse_coord_xpm[] = {
/* columns rows colors chars-per-pixel */
"32 32 2 1",
"  c black",
". c None",
/* pixels */
"................................",
"................................",
"................ ...............",
"................ ...............",
"................ ...............",
"................ ...............",
"................ ...............",
"................ ...............",
"................ ...............",
"................ ...............",
"................ ...............",
"................ ...............",
"................ ...............",
"................ ...............",
"................ ...............",
"................ ...............",
".............       ............",
"............. ..... ............",
"............. ..... ............",
".             .....            .",
"............. ..... ............",
".............       ............",
"................ ...............",
"................ ...............",
"................ ...............",
"................ ...............",
"................ ...............",
"................ ...............",
"................ ...............",
"................ ...............",
"................ ...............",
"................................"
};

#endif
