// #define CGAL_POINT_SET_DEMO_NO_SURFACE_MESHER

#ifndef CGAL_POINT_SET_DEMO_CONFIG_H
#define CGAL_POINT_SET_DEMO_CONFIG_H

#ifndef CGAL_POINT_SET_DEMO_NO_SURFACE_MESHER
#  define CGAL_POINT_SET_DEMO_USE_SURFACE_MESHER
#endif

#endif // CGAL_POINT_SET_DEMO_CONFIG_H
