#ifndef CGAL_SCENE_SURFACE_MESH_ITEM_CONFIG_H
#define CGAL_SCENE_SURFACE_MESH_ITEM_CONFIG_H

#ifdef scene_surface_mesh_item_EXPORTS
#  define SCENE_SURFACE_MESH_ITEM_EXPORT Q_DECL_EXPORT
#else
#  define SCENE_SURFACE_MESH_ITEM_EXPORT Q_DECL_IMPORT
#endif

#endif /* CGAL_SCENE_SURFACE_MESH_ITEM_CONFIG_H */
