#ifndef SCENE_NEF_POLYHEDRON_ITEM_CONFIG_H
#define SCENE_NEF_POLYHEDRON_ITEM_CONFIG_H

#ifdef scene_nef_polyhedron_item_EXPORTS
#  define SCENE_NEF_POLYHEDRON_ITEM_EXPORT Q_DECL_EXPORT
#else
#  define SCENE_NEF_POLYHEDRON_ITEM_EXPORT Q_DECL_IMPORT
#endif

#endif // SCENE_NEF_POLYHEDRON_ITEM_CONFIG_H
