#ifndef SCENE_POLYLINES_ITEM_CONFIG_H
#define SCENE_POLYLINES_ITEM_CONFIG_H

#ifdef scene_polylines_item_EXPORTS
#  define SCENE_POLYLINES_ITEM_EXPORT Q_DECL_EXPORT
#else
#  define SCENE_POLYLINES_ITEM_EXPORT Q_DECL_IMPORT
#endif

#endif // SCENE_POLYLINES_ITEM_CONFIG_H
