# Comments may appear but only before "HEADER".
# The number-type must be "integer", "rational", or "double" and must
# come before default-bound.
# The default-bound may be "nonnegative" or "free"; if no default-bound is
# given, "nonnegative" is assumed.
# The "D-MATRIX" section is optional, all others are mandatory.
HEADER
number-type: rational
number-of-variables: 3
number-of-constraints: 2
default-bound: nonnegative

CONSTRAINTS
1/1 2/3 3/1 <= 4/2
2/1 4/1 5/2  = 6/4

D-MATRIX
1/1 0/1 0/1
0/1 1/1 0/1
0/1 0/1 1/1

C-VECTOR-AND-BOUNDS
3/1 4/1 (0/1,) 5/1 (,4/1)

END
