# Comments may appear but only before "HEADER".
# The number-type must be "integer", "rational", or "double" and must
# come before default-bound.
# The default-bound may be "nonnegative" or "free"; if no default-bound is
# given, "nonnegative" is assumed.
# The "D-MATRIX" section is optional, all others are mandatory.
HEADER
number-type: integer
number-of-variables: 3
number-of-constraints: 2
default-bound: nonnegative

CONSTRAINTS
1 2 3 <= 4
2 4 5  = 6

D-MATRIX
1 0 0
0 1 0
0 0 1

C-VECTOR-AND-BOUNDS
3 4 (0 ,) 5 (,4)

END
