#ifndef SCENE_BASIC_OBJECTS_CONFIG_H
#define SCENE_BASIC_OBJECTS_CONFIG_H

#ifdef PS_demo_scene_basic_objects_EXPORTS
#  define SCENE_BASIC_OBJECTS_EXPORT Q_DECL_EXPORT
#else
#  define SCENE_BASIC_OBJECTS_EXPORT Q_DECL_IMPORT
#endif

#endif // SCENE_BASIC_OBJECTS_CONFIG_H
