deps:
	rm -f .*.deps; $(MAKE) renew_deps

.PHONY: renew_deps

.%.deps: %.C
	$(CGAL_CXX) $(CXXFLAGS) -M -MG $< | egrep -v '^ +/' > $@

DEPS_FILES = $(addprefix .,$(addsuffix .deps, $(basename $(wildcard *.C))))

renew_deps: $(DEPS_FILES)

-include $(DEPS_FILES)
