#!/bin/sh

if which python2 2>/dev/null >/dev/null; then 
    exec python2 /cygdrive/c/Users/stephen/Documents/Programming/CGALDev/Documentation/pkglist_filter.py "$1"
elif which python2.7 2>/dev/null >/dev/null; then 
    exec python2.7 /cygdrive/c/Users/stephen/Documents/Programming/CGALDev/Documentation/pkglist_filter.py "$1"
elif which python2.6 2>/dev/null >/dev/null; then 
    exec python2.6 /cygdrive/c/Users/stephen/Documents/Programming/CGALDev/Documentation/pkglist_filter.py "$1"
fi
