// #define CGAL_POLYHEDRON_DEMO_NO_NEF
// #define CGAL_POLYHEDRON_DEMO_NO_SURFACE_MESHER
// #define CGAL_POLYHEDRON_DEMO_NO_PARAMETRIZATION

#ifndef CGAL_POLYHEDRON_DEMO_CONFIG_H
#define CGAL_POLYHEDRON_DEMO_CONFIG_H

#ifndef CGAL_POLYHEDRON_DEMO_NO_PARAMETRIZATION
#  define CGAL_POLYHEDRON_DEMO_USE_PARAMETRIZATION
#endif

#ifndef CGAL_POLYHEDRON_DEMO_NO_NEF
#  define CGAL_POLYHEDRON_DEMO_USE_NEF
#endif

#ifndef CGAL_POLYHEDRON_DEMO_NO_SURFACE_MESHER
#  define CGAL_POLYHEDRON_DEMO_USE_SURFACE_MESHER
#endif

#ifndef CGAL_POINT_SET_PROCESSING_DO_NOT_COMPILE_DEPRECATED_V1_API
#  define CGAL_POINT_SET_PROCESSING_DO_NOT_COMPILE_DEPRECATED_V1_API
#endif

#endif // CGAL_POLYHEDRON_DEMO_CONFIG_H
