#ifndef CUSTOM_MANIPULATED_FRAME_CONFIG_H
#define CUSTOM_MANIPULATED_FRAME_CONFIG_H

#ifdef custom_manipulated_frame_EXPORTS
#  define CUSTOM_MANIPULATED_FRAME_EXPORT Q_DECL_EXPORT
#else
#  define CUSTOM_MANIPULATED_FRAME_EXPORT Q_DECL_IMPORT
#endif

#endif // CUSTOM_MANIPULATED_FRAME_CONFIG_H
