#ifndef POLYHEDRON_DEMO_CONFIG_H
#define POLYHEDRON_DEMO_CONFIG_H

#ifdef polyhedron_demo_EXPORTS
#  define POLYHEDRON_DEMO_EXPORT Q_DECL_EXPORT
#else
#  define POLYHEDRON_DEMO_EXPORT Q_DECL_IMPORT
#endif

#endif // POLYHEDRON_DEMO_CONFIG_H
