#ifndef SCENE_EDIT_POLYHEDRON_ITEM_CONFIG_2_H
#define SCENE_EDIT_POLYHEDRON_ITEM_CONFIG_2_H

#ifdef scene_edit_polyhedron_item_2_EXPORTS
#  define SCENE_EDIT_POLYHEDRON_ITEM_2_EXPORT Q_DECL_EXPORT
#else
#  define SCENE_EDIT_POLYHEDRON_ITEM_2_EXPORT Q_DECL_IMPORT
#endif

#endif // SCENE_EDIT_POLYHEDRON_ITEM_CONFIG_H
