#ifndef SCENE_POLYHEDRON_SELECTION_ITEM_CONFIG_H
#define SCENE_POLYHEDRON_SELECTION_ITEM_CONFIG_H

#if defined( scene_selection_item_EXPORTS )
#  define SCENE_POLYHEDRON_SELECTION_ITEM_EXPORT Q_DECL_EXPORT
#else
#  define SCENE_POLYHEDRON_SELECTION_ITEM_EXPORT Q_DECL_IMPORT
#endif

#endif // SCENE_POLYHEDRON_SELECTION_ITEM_CONFIG_H
