#ifndef SCENE_POLYGON_SOUP_ITEM_CONFIG_H
#define SCENE_POLYGON_SOUP_ITEM_CONFIG_H

#ifdef scene_polygon_soup_item_EXPORTS
#  define SCENE_POLYGON_SOUP_EXPORT Q_DECL_EXPORT
#else
#  define SCENE_POLYGON_SOUP_EXPORT Q_DECL_IMPORT
#endif

#endif // SCENE_POLYGON_SOUP_ITEM_CONFIG_H
