#ifndef SCENE_POLYHEDRON_ITEM_DECORATOR_CONFIG_H
#define SCENE_POLYHEDRON_ITEM_DECORATOR_CONFIG_H


#if defined(scene_item_decorator_EXPORTS)
#  define SCENE_POLYHEDRON_ITEM_DECORATOR_EXPORT Q_DECL_EXPORT
#else
#  define SCENE_POLYHEDRON_ITEM_DECORATOR_EXPORT Q_DECL_IMPORT
#endif


#endif // SCENE_POLYHEDRON_ITEM_DECORATOR_CONFIG_H
