#ifndef SCENE_COMBINATORIAL_MAP_ITEM_CONFIG_H
#define SCENE_COMBINATORIAL_MAP_ITEM_CONFIG_H

#ifdef scene_combinatorial_map_item_EXPORTS
#  define SCENE_COMBINATORIAL_MAP_ITEM_EXPORT Q_DECL_EXPORT
#else
#  define SCENE_COMBINATORIAL_MAP_ITEM_EXPORT Q_DECL_IMPORT
#endif

#endif // SCENE_COMBINATORIAL_MAP_ITEM_CONFIG_H
